<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

namespace SpecDb\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>specdb.query.AddExtraResponse</code>
 */
class AddExtraResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool ok = 1;</code>
     */
    protected $ok = false;
    /**
     * Generated from protobuf field <code>string message = 2;</code>
     */
    protected $message = '';
    /**
     * Generated from protobuf field <code>uint64 version = 3;</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>.specdb.query.Extra extra = 4;</code>
     */
    protected $extra = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $ok
     *     @type string $message
     *     @type int|string $version
     *     @type \SpecDb\Query\Extra $extra
     * }
     */
    public function __construct($data = NULL) {
        \SpecDb\Metadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool ok = 1;</code>
     * @return bool
     */
    public function getOk()
    {
        return $this->ok;
    }

    /**
     * Generated from protobuf field <code>bool ok = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setOk($var)
    {
        GPBUtil::checkBool($var);
        $this->ok = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 version = 3;</code>
     * @return int|string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>uint64 version = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkUint64($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.specdb.query.Extra extra = 4;</code>
     * @return \SpecDb\Query\Extra|null
     */
    public function getExtra()
    {
        return $this->extra;
    }

    public function hasExtra()
    {
        return isset($this->extra);
    }

    public function clearExtra()
    {
        unset($this->extra);
    }

    /**
     * Generated from protobuf field <code>.specdb.query.Extra extra = 4;</code>
     * @param \SpecDb\Query\Extra $var
     * @return $this
     */
    public function setExtra($var)
    {
        GPBUtil::checkMessage($var, \SpecDb\Query\Extra::class);
        $this->extra = $var;

        return $this;
    }

}

