<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

namespace SpecDb\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>specdb.query.AddExtraRequest</code>
 */
class AddExtraRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Identify the target spec and section to attach the extra to.
     *
     * Generated from protobuf field <code>string spec_name = 1;</code>
     */
    protected $spec_name = '';
    /**
     * Generated from protobuf field <code>string section_header = 2;</code>
     */
    protected $section_header = '';
    /**
     * Key within the section.extras map
     *
     * Generated from protobuf field <code>string key = 3;</code>
     */
    protected $key = '';
    /**
     * The typed extra payload (namespace + value + metadata)
     *
     * Generated from protobuf field <code>.specdb.query.Extra extra = 4;</code>
     */
    protected $extra = null;
    /**
     * Concurrency / behavior controls
     *
     * Generated from protobuf field <code>bool overwrite = 5;</code>
     */
    protected $overwrite = false;
    /**
     * Generated from protobuf field <code>uint64 expected_version = 6;</code>
     */
    protected $expected_version = 0;
    /**
     * Generated from protobuf field <code>string idempotency_key = 7;</code>
     */
    protected $idempotency_key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $spec_name
     *           Identify the target spec and section to attach the extra to.
     *     @type string $section_header
     *     @type string $key
     *           Key within the section.extras map
     *     @type \SpecDb\Query\Extra $extra
     *           The typed extra payload (namespace + value + metadata)
     *     @type bool $overwrite
     *           Concurrency / behavior controls
     *     @type int|string $expected_version
     *     @type string $idempotency_key
     * }
     */
    public function __construct($data = NULL) {
        \SpecDb\Metadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Identify the target spec and section to attach the extra to.
     *
     * Generated from protobuf field <code>string spec_name = 1;</code>
     * @return string
     */
    public function getSpecName()
    {
        return $this->spec_name;
    }

    /**
     * Identify the target spec and section to attach the extra to.
     *
     * Generated from protobuf field <code>string spec_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSpecName($var)
    {
        GPBUtil::checkString($var, True);
        $this->spec_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string section_header = 2;</code>
     * @return string
     */
    public function getSectionHeader()
    {
        return $this->section_header;
    }

    /**
     * Generated from protobuf field <code>string section_header = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSectionHeader($var)
    {
        GPBUtil::checkString($var, True);
        $this->section_header = $var;

        return $this;
    }

    /**
     * Key within the section.extras map
     *
     * Generated from protobuf field <code>string key = 3;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Key within the section.extras map
     *
     * Generated from protobuf field <code>string key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * The typed extra payload (namespace + value + metadata)
     *
     * Generated from protobuf field <code>.specdb.query.Extra extra = 4;</code>
     * @return \SpecDb\Query\Extra|null
     */
    public function getExtra()
    {
        return $this->extra;
    }

    public function hasExtra()
    {
        return isset($this->extra);
    }

    public function clearExtra()
    {
        unset($this->extra);
    }

    /**
     * The typed extra payload (namespace + value + metadata)
     *
     * Generated from protobuf field <code>.specdb.query.Extra extra = 4;</code>
     * @param \SpecDb\Query\Extra $var
     * @return $this
     */
    public function setExtra($var)
    {
        GPBUtil::checkMessage($var, \SpecDb\Query\Extra::class);
        $this->extra = $var;

        return $this;
    }

    /**
     * Concurrency / behavior controls
     *
     * Generated from protobuf field <code>bool overwrite = 5;</code>
     * @return bool
     */
    public function getOverwrite()
    {
        return $this->overwrite;
    }

    /**
     * Concurrency / behavior controls
     *
     * Generated from protobuf field <code>bool overwrite = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setOverwrite($var)
    {
        GPBUtil::checkBool($var);
        $this->overwrite = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 expected_version = 6;</code>
     * @return int|string
     */
    public function getExpectedVersion()
    {
        return $this->expected_version;
    }

    /**
     * Generated from protobuf field <code>uint64 expected_version = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpectedVersion($var)
    {
        GPBUtil::checkUint64($var);
        $this->expected_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string idempotency_key = 7;</code>
     * @return string
     */
    public function getIdempotencyKey()
    {
        return $this->idempotency_key;
    }

    /**
     * Generated from protobuf field <code>string idempotency_key = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setIdempotencyKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->idempotency_key = $var;

        return $this;
    }

}

