<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

namespace SpecDb\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>specdb.query.Apu</code>
 */
class Apu extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 core_count = 1;</code>
     */
    protected $core_count = 0;
    /**
     * Generated from protobuf field <code>uint32 thread_count = 2;</code>
     */
    protected $thread_count = 0;
    /**
     * Generated from protobuf field <code>string base_frequency = 3;</code>
     */
    protected $base_frequency = '';
    /**
     * Generated from protobuf field <code>uint32 shader_processor_count = 4;</code>
     */
    protected $shader_processor_count = 0;
    /**
     * CPU Specific
     *
     * Generated from protobuf field <code>optional string boost_frequency = 5;</code>
     */
    protected $boost_frequency = null;
    /**
     * Generated from protobuf field <code>optional string xfr_frequency = 6;</code>
     */
    protected $xfr_frequency = null;
    /**
     * Generated from protobuf field <code>optional string socket = 7;</code>
     */
    protected $socket = null;
    /**
     * Generated from protobuf field <code>optional string stepping = 8;</code>
     */
    protected $stepping = null;
    /**
     * Generated from protobuf field <code>optional string l1_cache_data = 9;</code>
     */
    protected $l1_cache_data = null;
    /**
     * Generated from protobuf field <code>optional string l1_cache_instruction = 10;</code>
     */
    protected $l1_cache_instruction = null;
    /**
     * Generated from protobuf field <code>optional string l2_cache_total = 11;</code>
     */
    protected $l2_cache_total = null;
    /**
     * Generated from protobuf field <code>optional string l3_cache_total = 12;</code>
     */
    protected $l3_cache_total = null;
    /**
     * Generated from protobuf field <code>optional string memory_type = 13;</code>
     */
    protected $memory_type = null;
    /**
     * Generated from protobuf field <code>optional uint32 pcie_5_0_lanes = 14;</code>
     */
    protected $pcie_5_0_lanes = null;
    /**
     * Generated from protobuf field <code>optional uint32 pcie_4_0_lanes = 15;</code>
     */
    protected $pcie_4_0_lanes = null;
    /**
     * Generated from protobuf field <code>optional uint32 pcie_3_0_lanes = 16;</code>
     */
    protected $pcie_3_0_lanes = null;
    /**
     * Generated from protobuf field <code>optional uint32 pcie_2_0_lanes = 17;</code>
     */
    protected $pcie_2_0_lanes = null;
    /**
     * Generated from protobuf field <code>optional uint32 pcie_1_0_lanes = 18;</code>
     */
    protected $pcie_1_0_lanes = null;
    /**
     * Generated from protobuf field <code>optional string avx_sse_mmx = 19;</code>
     */
    protected $avx_sse_mmx = null;
    /**
     * Generated from protobuf field <code>optional bool fma4 = 20;</code>
     */
    protected $fma4 = null;
    /**
     * Generated from protobuf field <code>optional bool fma3 = 21;</code>
     */
    protected $fma3 = null;
    /**
     * Generated from protobuf field <code>optional string bmi = 22;</code>
     */
    protected $bmi = null;
    /**
     * Generated from protobuf field <code>optional bool aes = 23;</code>
     */
    protected $aes = null;
    /**
     * Generated from protobuf field <code>optional bool sha = 24;</code>
     */
    protected $sha = null;
    /**
     * Generated from protobuf field <code>repeated string other_extensions = 25;</code>
     */
    private $other_extensions;
    /**
     * Generated from protobuf field <code>optional bool unlocked = 26;</code>
     */
    protected $unlocked = null;
    /**
     * Generated from protobuf field <code>optional bool xfr_support = 27;</code>
     */
    protected $xfr_support = null;
    /**
     * Generated from protobuf field <code>optional string max_memory_channels = 28;</code>
     */
    protected $max_memory_channels = null;
    /**
     * Generated from protobuf field <code>optional string max_memory_frequency = 29;</code>
     */
    protected $max_memory_frequency = null;
    /**
     * Generated from protobuf field <code>repeated string compatable_chipsets = 30;</code>
     */
    private $compatable_chipsets;
    /**
     * Hybrid architecture details
     *
     * Generated from protobuf field <code>optional string performance_core_base_frequency = 31;</code>
     */
    protected $performance_core_base_frequency = null;
    /**
     * Generated from protobuf field <code>optional string efficient_core_base_frequency = 32;</code>
     */
    protected $efficient_core_base_frequency = null;
    /**
     * Generated from protobuf field <code>optional string performance_core_boost_frequency = 33;</code>
     */
    protected $performance_core_boost_frequency = null;
    /**
     * Generated from protobuf field <code>optional string efficient_core_boost_frequency = 34;</code>
     */
    protected $efficient_core_boost_frequency = null;
    /**
     * Generated from protobuf field <code>optional uint32 performance_core_count = 35;</code>
     */
    protected $performance_core_count = null;
    /**
     * Generated from protobuf field <code>optional uint32 efficient_core_count = 36;</code>
     */
    protected $efficient_core_count = null;
    /**
     * Generated from protobuf field <code>optional uint32 performance_thread_count = 37;</code>
     */
    protected $performance_thread_count = null;
    /**
     * Generated from protobuf field <code>optional uint32 efficient_thread_count = 38;</code>
     */
    protected $efficient_thread_count = null;
    /**
     * Generated from protobuf field <code>optional bool ctdp_support = 39;</code>
     */
    protected $ctdp_support = null;
    /**
     * Generated from protobuf field <code>optional string efficient_core_architecture = 40;</code>
     */
    protected $efficient_core_architecture = null;
    /**
     * Shared
     *
     * Generated from protobuf field <code>optional string manufacturer = 41;</code>
     */
    protected $manufacturer = null;
    /**
     * Generated from protobuf field <code>repeated string market = 42;</code>
     */
    private $market;
    /**
     * Generated from protobuf field <code>optional string architecture = 43;</code>
     */
    protected $architecture = null;
    /**
     * Generated from protobuf field <code>optional string lithography = 44;</code>
     */
    protected $lithography = null;
    /**
     * Generated from protobuf field <code>optional string release_date = 45;</code>
     */
    protected $release_date = null;
    /**
     * gpu
     *
     * Generated from protobuf field <code>optional string tdp = 46;</code>
     */
    protected $tdp = null;
    /**
     * Generated from protobuf field <code>optional string gpu_base_frequency = 47;</code>
     */
    protected $gpu_base_frequency = null;
    /**
     * Generated from protobuf field <code>optional string direct_x_support = 48;</code>
     */
    protected $direct_x_support = null;
    /**
     * Generated from protobuf field <code>optional string open_gl_support = 49;</code>
     */
    protected $open_gl_support = null;
    /**
     * Generated from protobuf field <code>optional string open_cl_support = 50;</code>
     */
    protected $open_cl_support = null;
    /**
     * Generated from protobuf field <code>optional string vulkan_support = 51;</code>
     */
    protected $vulkan_support = null;
    /**
     * Generated from protobuf field <code>optional string vram_type = 52;</code>
     */
    protected $vram_type = null;
    /**
     * Generated from protobuf field <code>optional uint32 render_output_unit_count = 53;</code>
     */
    protected $render_output_unit_count = null;
    /**
     * Generated from protobuf field <code>optional uint32 texture_mapping_unit_count = 54;</code>
     */
    protected $texture_mapping_unit_count = null;
    /**
     * Generated from protobuf field <code>optional string gpu_model = 55;</code>
     */
    protected $gpu_model = null;
    /**
     * Generated from protobuf field <code>optional string hlsl_shader_model = 56;</code>
     */
    protected $hlsl_shader_model = null;
    /**
     * Generated from protobuf field <code>optional string gpu_boost_frequency = 57;</code>
     */
    protected $gpu_boost_frequency = null;
    /**
     * Generated from protobuf field <code>optional uint32 ray_tracing_cores = 58;</code>
     */
    protected $ray_tracing_cores = null;
    /**
     * Generated from protobuf field <code>optional uint32 tensor_cores = 59;</code>
     */
    protected $tensor_cores = null;
    /**
     * Generated from protobuf field <code>repeated string hardware_accelerated_encoding = 60;</code>
     */
    private $hardware_accelerated_encoding;
    /**
     * Generated from protobuf field <code>repeated string hardware_accelerated_decoding = 61;</code>
     */
    private $hardware_accelerated_decoding;
    /**
     * Generated from protobuf field <code>optional string module_count = 62;</code>
     */
    protected $module_count = null;
    /**
     * Generated from protobuf field <code>optional uint32 pixel_shaders = 63;</code>
     */
    protected $pixel_shaders = null;
    /**
     * Generated from protobuf field <code>optional string max_displays = 64;</code>
     */
    protected $max_displays = null;
    /**
     * Generated from protobuf field <code>optional string crossfire_support = 65;</code>
     */
    protected $crossfire_support = null;
    /**
     * Generated from protobuf field <code>optional string free_sync_support = 66;</code>
     */
    protected $free_sync_support = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $core_count
     *     @type int $thread_count
     *     @type string $base_frequency
     *     @type int $shader_processor_count
     *     @type string $boost_frequency
     *           CPU Specific
     *     @type string $xfr_frequency
     *     @type string $socket
     *     @type string $stepping
     *     @type string $l1_cache_data
     *     @type string $l1_cache_instruction
     *     @type string $l2_cache_total
     *     @type string $l3_cache_total
     *     @type string $memory_type
     *     @type int $pcie_5_0_lanes
     *     @type int $pcie_4_0_lanes
     *     @type int $pcie_3_0_lanes
     *     @type int $pcie_2_0_lanes
     *     @type int $pcie_1_0_lanes
     *     @type string $avx_sse_mmx
     *     @type bool $fma4
     *     @type bool $fma3
     *     @type string $bmi
     *     @type bool $aes
     *     @type bool $sha
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $other_extensions
     *     @type bool $unlocked
     *     @type bool $xfr_support
     *     @type string $max_memory_channels
     *     @type string $max_memory_frequency
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $compatable_chipsets
     *     @type string $performance_core_base_frequency
     *           Hybrid architecture details
     *     @type string $efficient_core_base_frequency
     *     @type string $performance_core_boost_frequency
     *     @type string $efficient_core_boost_frequency
     *     @type int $performance_core_count
     *     @type int $efficient_core_count
     *     @type int $performance_thread_count
     *     @type int $efficient_thread_count
     *     @type bool $ctdp_support
     *     @type string $efficient_core_architecture
     *     @type string $manufacturer
     *           Shared
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $market
     *     @type string $architecture
     *     @type string $lithography
     *     @type string $release_date
     *     @type string $tdp
     *           gpu
     *     @type string $gpu_base_frequency
     *     @type string $direct_x_support
     *     @type string $open_gl_support
     *     @type string $open_cl_support
     *     @type string $vulkan_support
     *     @type string $vram_type
     *     @type int $render_output_unit_count
     *     @type int $texture_mapping_unit_count
     *     @type string $gpu_model
     *     @type string $hlsl_shader_model
     *     @type string $gpu_boost_frequency
     *     @type int $ray_tracing_cores
     *     @type int $tensor_cores
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $hardware_accelerated_encoding
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $hardware_accelerated_decoding
     *     @type string $module_count
     *     @type int $pixel_shaders
     *     @type string $max_displays
     *     @type string $crossfire_support
     *     @type string $free_sync_support
     * }
     */
    public function __construct($data = NULL) {
        \SpecDb\Metadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 core_count = 1;</code>
     * @return int
     */
    public function getCoreCount()
    {
        return $this->core_count;
    }

    /**
     * Generated from protobuf field <code>uint32 core_count = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCoreCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->core_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 thread_count = 2;</code>
     * @return int
     */
    public function getThreadCount()
    {
        return $this->thread_count;
    }

    /**
     * Generated from protobuf field <code>uint32 thread_count = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setThreadCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->thread_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string base_frequency = 3;</code>
     * @return string
     */
    public function getBaseFrequency()
    {
        return $this->base_frequency;
    }

    /**
     * Generated from protobuf field <code>string base_frequency = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBaseFrequency($var)
    {
        GPBUtil::checkString($var, True);
        $this->base_frequency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 shader_processor_count = 4;</code>
     * @return int
     */
    public function getShaderProcessorCount()
    {
        return $this->shader_processor_count;
    }

    /**
     * Generated from protobuf field <code>uint32 shader_processor_count = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setShaderProcessorCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->shader_processor_count = $var;

        return $this;
    }

    /**
     * CPU Specific
     *
     * Generated from protobuf field <code>optional string boost_frequency = 5;</code>
     * @return string
     */
    public function getBoostFrequency()
    {
        return isset($this->boost_frequency) ? $this->boost_frequency : '';
    }

    public function hasBoostFrequency()
    {
        return isset($this->boost_frequency);
    }

    public function clearBoostFrequency()
    {
        unset($this->boost_frequency);
    }

    /**
     * CPU Specific
     *
     * Generated from protobuf field <code>optional string boost_frequency = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setBoostFrequency($var)
    {
        GPBUtil::checkString($var, True);
        $this->boost_frequency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string xfr_frequency = 6;</code>
     * @return string
     */
    public function getXfrFrequency()
    {
        return isset($this->xfr_frequency) ? $this->xfr_frequency : '';
    }

    public function hasXfrFrequency()
    {
        return isset($this->xfr_frequency);
    }

    public function clearXfrFrequency()
    {
        unset($this->xfr_frequency);
    }

    /**
     * Generated from protobuf field <code>optional string xfr_frequency = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setXfrFrequency($var)
    {
        GPBUtil::checkString($var, True);
        $this->xfr_frequency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string socket = 7;</code>
     * @return string
     */
    public function getSocket()
    {
        return isset($this->socket) ? $this->socket : '';
    }

    public function hasSocket()
    {
        return isset($this->socket);
    }

    public function clearSocket()
    {
        unset($this->socket);
    }

    /**
     * Generated from protobuf field <code>optional string socket = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setSocket($var)
    {
        GPBUtil::checkString($var, True);
        $this->socket = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string stepping = 8;</code>
     * @return string
     */
    public function getStepping()
    {
        return isset($this->stepping) ? $this->stepping : '';
    }

    public function hasStepping()
    {
        return isset($this->stepping);
    }

    public function clearStepping()
    {
        unset($this->stepping);
    }

    /**
     * Generated from protobuf field <code>optional string stepping = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setStepping($var)
    {
        GPBUtil::checkString($var, True);
        $this->stepping = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string l1_cache_data = 9;</code>
     * @return string
     */
    public function getL1CacheData()
    {
        return isset($this->l1_cache_data) ? $this->l1_cache_data : '';
    }

    public function hasL1CacheData()
    {
        return isset($this->l1_cache_data);
    }

    public function clearL1CacheData()
    {
        unset($this->l1_cache_data);
    }

    /**
     * Generated from protobuf field <code>optional string l1_cache_data = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setL1CacheData($var)
    {
        GPBUtil::checkString($var, True);
        $this->l1_cache_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string l1_cache_instruction = 10;</code>
     * @return string
     */
    public function getL1CacheInstruction()
    {
        return isset($this->l1_cache_instruction) ? $this->l1_cache_instruction : '';
    }

    public function hasL1CacheInstruction()
    {
        return isset($this->l1_cache_instruction);
    }

    public function clearL1CacheInstruction()
    {
        unset($this->l1_cache_instruction);
    }

    /**
     * Generated from protobuf field <code>optional string l1_cache_instruction = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setL1CacheInstruction($var)
    {
        GPBUtil::checkString($var, True);
        $this->l1_cache_instruction = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string l2_cache_total = 11;</code>
     * @return string
     */
    public function getL2CacheTotal()
    {
        return isset($this->l2_cache_total) ? $this->l2_cache_total : '';
    }

    public function hasL2CacheTotal()
    {
        return isset($this->l2_cache_total);
    }

    public function clearL2CacheTotal()
    {
        unset($this->l2_cache_total);
    }

    /**
     * Generated from protobuf field <code>optional string l2_cache_total = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setL2CacheTotal($var)
    {
        GPBUtil::checkString($var, True);
        $this->l2_cache_total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string l3_cache_total = 12;</code>
     * @return string
     */
    public function getL3CacheTotal()
    {
        return isset($this->l3_cache_total) ? $this->l3_cache_total : '';
    }

    public function hasL3CacheTotal()
    {
        return isset($this->l3_cache_total);
    }

    public function clearL3CacheTotal()
    {
        unset($this->l3_cache_total);
    }

    /**
     * Generated from protobuf field <code>optional string l3_cache_total = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setL3CacheTotal($var)
    {
        GPBUtil::checkString($var, True);
        $this->l3_cache_total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string memory_type = 13;</code>
     * @return string
     */
    public function getMemoryType()
    {
        return isset($this->memory_type) ? $this->memory_type : '';
    }

    public function hasMemoryType()
    {
        return isset($this->memory_type);
    }

    public function clearMemoryType()
    {
        unset($this->memory_type);
    }

    /**
     * Generated from protobuf field <code>optional string memory_type = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setMemoryType($var)
    {
        GPBUtil::checkString($var, True);
        $this->memory_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 pcie_5_0_lanes = 14;</code>
     * @return int
     */
    public function getPcie50Lanes()
    {
        return isset($this->pcie_5_0_lanes) ? $this->pcie_5_0_lanes : 0;
    }

    public function hasPcie50Lanes()
    {
        return isset($this->pcie_5_0_lanes);
    }

    public function clearPcie50Lanes()
    {
        unset($this->pcie_5_0_lanes);
    }

    /**
     * Generated from protobuf field <code>optional uint32 pcie_5_0_lanes = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setPcie50Lanes($var)
    {
        GPBUtil::checkUint32($var);
        $this->pcie_5_0_lanes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 pcie_4_0_lanes = 15;</code>
     * @return int
     */
    public function getPcie40Lanes()
    {
        return isset($this->pcie_4_0_lanes) ? $this->pcie_4_0_lanes : 0;
    }

    public function hasPcie40Lanes()
    {
        return isset($this->pcie_4_0_lanes);
    }

    public function clearPcie40Lanes()
    {
        unset($this->pcie_4_0_lanes);
    }

    /**
     * Generated from protobuf field <code>optional uint32 pcie_4_0_lanes = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setPcie40Lanes($var)
    {
        GPBUtil::checkUint32($var);
        $this->pcie_4_0_lanes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 pcie_3_0_lanes = 16;</code>
     * @return int
     */
    public function getPcie30Lanes()
    {
        return isset($this->pcie_3_0_lanes) ? $this->pcie_3_0_lanes : 0;
    }

    public function hasPcie30Lanes()
    {
        return isset($this->pcie_3_0_lanes);
    }

    public function clearPcie30Lanes()
    {
        unset($this->pcie_3_0_lanes);
    }

    /**
     * Generated from protobuf field <code>optional uint32 pcie_3_0_lanes = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setPcie30Lanes($var)
    {
        GPBUtil::checkUint32($var);
        $this->pcie_3_0_lanes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 pcie_2_0_lanes = 17;</code>
     * @return int
     */
    public function getPcie20Lanes()
    {
        return isset($this->pcie_2_0_lanes) ? $this->pcie_2_0_lanes : 0;
    }

    public function hasPcie20Lanes()
    {
        return isset($this->pcie_2_0_lanes);
    }

    public function clearPcie20Lanes()
    {
        unset($this->pcie_2_0_lanes);
    }

    /**
     * Generated from protobuf field <code>optional uint32 pcie_2_0_lanes = 17;</code>
     * @param int $var
     * @return $this
     */
    public function setPcie20Lanes($var)
    {
        GPBUtil::checkUint32($var);
        $this->pcie_2_0_lanes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 pcie_1_0_lanes = 18;</code>
     * @return int
     */
    public function getPcie10Lanes()
    {
        return isset($this->pcie_1_0_lanes) ? $this->pcie_1_0_lanes : 0;
    }

    public function hasPcie10Lanes()
    {
        return isset($this->pcie_1_0_lanes);
    }

    public function clearPcie10Lanes()
    {
        unset($this->pcie_1_0_lanes);
    }

    /**
     * Generated from protobuf field <code>optional uint32 pcie_1_0_lanes = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setPcie10Lanes($var)
    {
        GPBUtil::checkUint32($var);
        $this->pcie_1_0_lanes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string avx_sse_mmx = 19;</code>
     * @return string
     */
    public function getAvxSseMmx()
    {
        return isset($this->avx_sse_mmx) ? $this->avx_sse_mmx : '';
    }

    public function hasAvxSseMmx()
    {
        return isset($this->avx_sse_mmx);
    }

    public function clearAvxSseMmx()
    {
        unset($this->avx_sse_mmx);
    }

    /**
     * Generated from protobuf field <code>optional string avx_sse_mmx = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setAvxSseMmx($var)
    {
        GPBUtil::checkString($var, True);
        $this->avx_sse_mmx = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool fma4 = 20;</code>
     * @return bool
     */
    public function getFma4()
    {
        return isset($this->fma4) ? $this->fma4 : false;
    }

    public function hasFma4()
    {
        return isset($this->fma4);
    }

    public function clearFma4()
    {
        unset($this->fma4);
    }

    /**
     * Generated from protobuf field <code>optional bool fma4 = 20;</code>
     * @param bool $var
     * @return $this
     */
    public function setFma4($var)
    {
        GPBUtil::checkBool($var);
        $this->fma4 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool fma3 = 21;</code>
     * @return bool
     */
    public function getFma3()
    {
        return isset($this->fma3) ? $this->fma3 : false;
    }

    public function hasFma3()
    {
        return isset($this->fma3);
    }

    public function clearFma3()
    {
        unset($this->fma3);
    }

    /**
     * Generated from protobuf field <code>optional bool fma3 = 21;</code>
     * @param bool $var
     * @return $this
     */
    public function setFma3($var)
    {
        GPBUtil::checkBool($var);
        $this->fma3 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string bmi = 22;</code>
     * @return string
     */
    public function getBmi()
    {
        return isset($this->bmi) ? $this->bmi : '';
    }

    public function hasBmi()
    {
        return isset($this->bmi);
    }

    public function clearBmi()
    {
        unset($this->bmi);
    }

    /**
     * Generated from protobuf field <code>optional string bmi = 22;</code>
     * @param string $var
     * @return $this
     */
    public function setBmi($var)
    {
        GPBUtil::checkString($var, True);
        $this->bmi = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool aes = 23;</code>
     * @return bool
     */
    public function getAes()
    {
        return isset($this->aes) ? $this->aes : false;
    }

    public function hasAes()
    {
        return isset($this->aes);
    }

    public function clearAes()
    {
        unset($this->aes);
    }

    /**
     * Generated from protobuf field <code>optional bool aes = 23;</code>
     * @param bool $var
     * @return $this
     */
    public function setAes($var)
    {
        GPBUtil::checkBool($var);
        $this->aes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool sha = 24;</code>
     * @return bool
     */
    public function getSha()
    {
        return isset($this->sha) ? $this->sha : false;
    }

    public function hasSha()
    {
        return isset($this->sha);
    }

    public function clearSha()
    {
        unset($this->sha);
    }

    /**
     * Generated from protobuf field <code>optional bool sha = 24;</code>
     * @param bool $var
     * @return $this
     */
    public function setSha($var)
    {
        GPBUtil::checkBool($var);
        $this->sha = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string other_extensions = 25;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOtherExtensions()
    {
        return $this->other_extensions;
    }

    /**
     * Generated from protobuf field <code>repeated string other_extensions = 25;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOtherExtensions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->other_extensions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool unlocked = 26;</code>
     * @return bool
     */
    public function getUnlocked()
    {
        return isset($this->unlocked) ? $this->unlocked : false;
    }

    public function hasUnlocked()
    {
        return isset($this->unlocked);
    }

    public function clearUnlocked()
    {
        unset($this->unlocked);
    }

    /**
     * Generated from protobuf field <code>optional bool unlocked = 26;</code>
     * @param bool $var
     * @return $this
     */
    public function setUnlocked($var)
    {
        GPBUtil::checkBool($var);
        $this->unlocked = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool xfr_support = 27;</code>
     * @return bool
     */
    public function getXfrSupport()
    {
        return isset($this->xfr_support) ? $this->xfr_support : false;
    }

    public function hasXfrSupport()
    {
        return isset($this->xfr_support);
    }

    public function clearXfrSupport()
    {
        unset($this->xfr_support);
    }

    /**
     * Generated from protobuf field <code>optional bool xfr_support = 27;</code>
     * @param bool $var
     * @return $this
     */
    public function setXfrSupport($var)
    {
        GPBUtil::checkBool($var);
        $this->xfr_support = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string max_memory_channels = 28;</code>
     * @return string
     */
    public function getMaxMemoryChannels()
    {
        return isset($this->max_memory_channels) ? $this->max_memory_channels : '';
    }

    public function hasMaxMemoryChannels()
    {
        return isset($this->max_memory_channels);
    }

    public function clearMaxMemoryChannels()
    {
        unset($this->max_memory_channels);
    }

    /**
     * Generated from protobuf field <code>optional string max_memory_channels = 28;</code>
     * @param string $var
     * @return $this
     */
    public function setMaxMemoryChannels($var)
    {
        GPBUtil::checkString($var, True);
        $this->max_memory_channels = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string max_memory_frequency = 29;</code>
     * @return string
     */
    public function getMaxMemoryFrequency()
    {
        return isset($this->max_memory_frequency) ? $this->max_memory_frequency : '';
    }

    public function hasMaxMemoryFrequency()
    {
        return isset($this->max_memory_frequency);
    }

    public function clearMaxMemoryFrequency()
    {
        unset($this->max_memory_frequency);
    }

    /**
     * Generated from protobuf field <code>optional string max_memory_frequency = 29;</code>
     * @param string $var
     * @return $this
     */
    public function setMaxMemoryFrequency($var)
    {
        GPBUtil::checkString($var, True);
        $this->max_memory_frequency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string compatable_chipsets = 30;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCompatableChipsets()
    {
        return $this->compatable_chipsets;
    }

    /**
     * Generated from protobuf field <code>repeated string compatable_chipsets = 30;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCompatableChipsets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->compatable_chipsets = $arr;

        return $this;
    }

    /**
     * Hybrid architecture details
     *
     * Generated from protobuf field <code>optional string performance_core_base_frequency = 31;</code>
     * @return string
     */
    public function getPerformanceCoreBaseFrequency()
    {
        return isset($this->performance_core_base_frequency) ? $this->performance_core_base_frequency : '';
    }

    public function hasPerformanceCoreBaseFrequency()
    {
        return isset($this->performance_core_base_frequency);
    }

    public function clearPerformanceCoreBaseFrequency()
    {
        unset($this->performance_core_base_frequency);
    }

    /**
     * Hybrid architecture details
     *
     * Generated from protobuf field <code>optional string performance_core_base_frequency = 31;</code>
     * @param string $var
     * @return $this
     */
    public function setPerformanceCoreBaseFrequency($var)
    {
        GPBUtil::checkString($var, True);
        $this->performance_core_base_frequency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string efficient_core_base_frequency = 32;</code>
     * @return string
     */
    public function getEfficientCoreBaseFrequency()
    {
        return isset($this->efficient_core_base_frequency) ? $this->efficient_core_base_frequency : '';
    }

    public function hasEfficientCoreBaseFrequency()
    {
        return isset($this->efficient_core_base_frequency);
    }

    public function clearEfficientCoreBaseFrequency()
    {
        unset($this->efficient_core_base_frequency);
    }

    /**
     * Generated from protobuf field <code>optional string efficient_core_base_frequency = 32;</code>
     * @param string $var
     * @return $this
     */
    public function setEfficientCoreBaseFrequency($var)
    {
        GPBUtil::checkString($var, True);
        $this->efficient_core_base_frequency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string performance_core_boost_frequency = 33;</code>
     * @return string
     */
    public function getPerformanceCoreBoostFrequency()
    {
        return isset($this->performance_core_boost_frequency) ? $this->performance_core_boost_frequency : '';
    }

    public function hasPerformanceCoreBoostFrequency()
    {
        return isset($this->performance_core_boost_frequency);
    }

    public function clearPerformanceCoreBoostFrequency()
    {
        unset($this->performance_core_boost_frequency);
    }

    /**
     * Generated from protobuf field <code>optional string performance_core_boost_frequency = 33;</code>
     * @param string $var
     * @return $this
     */
    public function setPerformanceCoreBoostFrequency($var)
    {
        GPBUtil::checkString($var, True);
        $this->performance_core_boost_frequency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string efficient_core_boost_frequency = 34;</code>
     * @return string
     */
    public function getEfficientCoreBoostFrequency()
    {
        return isset($this->efficient_core_boost_frequency) ? $this->efficient_core_boost_frequency : '';
    }

    public function hasEfficientCoreBoostFrequency()
    {
        return isset($this->efficient_core_boost_frequency);
    }

    public function clearEfficientCoreBoostFrequency()
    {
        unset($this->efficient_core_boost_frequency);
    }

    /**
     * Generated from protobuf field <code>optional string efficient_core_boost_frequency = 34;</code>
     * @param string $var
     * @return $this
     */
    public function setEfficientCoreBoostFrequency($var)
    {
        GPBUtil::checkString($var, True);
        $this->efficient_core_boost_frequency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 performance_core_count = 35;</code>
     * @return int
     */
    public function getPerformanceCoreCount()
    {
        return isset($this->performance_core_count) ? $this->performance_core_count : 0;
    }

    public function hasPerformanceCoreCount()
    {
        return isset($this->performance_core_count);
    }

    public function clearPerformanceCoreCount()
    {
        unset($this->performance_core_count);
    }

    /**
     * Generated from protobuf field <code>optional uint32 performance_core_count = 35;</code>
     * @param int $var
     * @return $this
     */
    public function setPerformanceCoreCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->performance_core_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 efficient_core_count = 36;</code>
     * @return int
     */
    public function getEfficientCoreCount()
    {
        return isset($this->efficient_core_count) ? $this->efficient_core_count : 0;
    }

    public function hasEfficientCoreCount()
    {
        return isset($this->efficient_core_count);
    }

    public function clearEfficientCoreCount()
    {
        unset($this->efficient_core_count);
    }

    /**
     * Generated from protobuf field <code>optional uint32 efficient_core_count = 36;</code>
     * @param int $var
     * @return $this
     */
    public function setEfficientCoreCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->efficient_core_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 performance_thread_count = 37;</code>
     * @return int
     */
    public function getPerformanceThreadCount()
    {
        return isset($this->performance_thread_count) ? $this->performance_thread_count : 0;
    }

    public function hasPerformanceThreadCount()
    {
        return isset($this->performance_thread_count);
    }

    public function clearPerformanceThreadCount()
    {
        unset($this->performance_thread_count);
    }

    /**
     * Generated from protobuf field <code>optional uint32 performance_thread_count = 37;</code>
     * @param int $var
     * @return $this
     */
    public function setPerformanceThreadCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->performance_thread_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 efficient_thread_count = 38;</code>
     * @return int
     */
    public function getEfficientThreadCount()
    {
        return isset($this->efficient_thread_count) ? $this->efficient_thread_count : 0;
    }

    public function hasEfficientThreadCount()
    {
        return isset($this->efficient_thread_count);
    }

    public function clearEfficientThreadCount()
    {
        unset($this->efficient_thread_count);
    }

    /**
     * Generated from protobuf field <code>optional uint32 efficient_thread_count = 38;</code>
     * @param int $var
     * @return $this
     */
    public function setEfficientThreadCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->efficient_thread_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool ctdp_support = 39;</code>
     * @return bool
     */
    public function getCtdpSupport()
    {
        return isset($this->ctdp_support) ? $this->ctdp_support : false;
    }

    public function hasCtdpSupport()
    {
        return isset($this->ctdp_support);
    }

    public function clearCtdpSupport()
    {
        unset($this->ctdp_support);
    }

    /**
     * Generated from protobuf field <code>optional bool ctdp_support = 39;</code>
     * @param bool $var
     * @return $this
     */
    public function setCtdpSupport($var)
    {
        GPBUtil::checkBool($var);
        $this->ctdp_support = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string efficient_core_architecture = 40;</code>
     * @return string
     */
    public function getEfficientCoreArchitecture()
    {
        return isset($this->efficient_core_architecture) ? $this->efficient_core_architecture : '';
    }

    public function hasEfficientCoreArchitecture()
    {
        return isset($this->efficient_core_architecture);
    }

    public function clearEfficientCoreArchitecture()
    {
        unset($this->efficient_core_architecture);
    }

    /**
     * Generated from protobuf field <code>optional string efficient_core_architecture = 40;</code>
     * @param string $var
     * @return $this
     */
    public function setEfficientCoreArchitecture($var)
    {
        GPBUtil::checkString($var, True);
        $this->efficient_core_architecture = $var;

        return $this;
    }

    /**
     * Shared
     *
     * Generated from protobuf field <code>optional string manufacturer = 41;</code>
     * @return string
     */
    public function getManufacturer()
    {
        return isset($this->manufacturer) ? $this->manufacturer : '';
    }

    public function hasManufacturer()
    {
        return isset($this->manufacturer);
    }

    public function clearManufacturer()
    {
        unset($this->manufacturer);
    }

    /**
     * Shared
     *
     * Generated from protobuf field <code>optional string manufacturer = 41;</code>
     * @param string $var
     * @return $this
     */
    public function setManufacturer($var)
    {
        GPBUtil::checkString($var, True);
        $this->manufacturer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string market = 42;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMarket()
    {
        return $this->market;
    }

    /**
     * Generated from protobuf field <code>repeated string market = 42;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMarket($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->market = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string architecture = 43;</code>
     * @return string
     */
    public function getArchitecture()
    {
        return isset($this->architecture) ? $this->architecture : '';
    }

    public function hasArchitecture()
    {
        return isset($this->architecture);
    }

    public function clearArchitecture()
    {
        unset($this->architecture);
    }

    /**
     * Generated from protobuf field <code>optional string architecture = 43;</code>
     * @param string $var
     * @return $this
     */
    public function setArchitecture($var)
    {
        GPBUtil::checkString($var, True);
        $this->architecture = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string lithography = 44;</code>
     * @return string
     */
    public function getLithography()
    {
        return isset($this->lithography) ? $this->lithography : '';
    }

    public function hasLithography()
    {
        return isset($this->lithography);
    }

    public function clearLithography()
    {
        unset($this->lithography);
    }

    /**
     * Generated from protobuf field <code>optional string lithography = 44;</code>
     * @param string $var
     * @return $this
     */
    public function setLithography($var)
    {
        GPBUtil::checkString($var, True);
        $this->lithography = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string release_date = 45;</code>
     * @return string
     */
    public function getReleaseDate()
    {
        return isset($this->release_date) ? $this->release_date : '';
    }

    public function hasReleaseDate()
    {
        return isset($this->release_date);
    }

    public function clearReleaseDate()
    {
        unset($this->release_date);
    }

    /**
     * Generated from protobuf field <code>optional string release_date = 45;</code>
     * @param string $var
     * @return $this
     */
    public function setReleaseDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->release_date = $var;

        return $this;
    }

    /**
     * gpu
     *
     * Generated from protobuf field <code>optional string tdp = 46;</code>
     * @return string
     */
    public function getTdp()
    {
        return isset($this->tdp) ? $this->tdp : '';
    }

    public function hasTdp()
    {
        return isset($this->tdp);
    }

    public function clearTdp()
    {
        unset($this->tdp);
    }

    /**
     * gpu
     *
     * Generated from protobuf field <code>optional string tdp = 46;</code>
     * @param string $var
     * @return $this
     */
    public function setTdp($var)
    {
        GPBUtil::checkString($var, True);
        $this->tdp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string gpu_base_frequency = 47;</code>
     * @return string
     */
    public function getGpuBaseFrequency()
    {
        return isset($this->gpu_base_frequency) ? $this->gpu_base_frequency : '';
    }

    public function hasGpuBaseFrequency()
    {
        return isset($this->gpu_base_frequency);
    }

    public function clearGpuBaseFrequency()
    {
        unset($this->gpu_base_frequency);
    }

    /**
     * Generated from protobuf field <code>optional string gpu_base_frequency = 47;</code>
     * @param string $var
     * @return $this
     */
    public function setGpuBaseFrequency($var)
    {
        GPBUtil::checkString($var, True);
        $this->gpu_base_frequency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string direct_x_support = 48;</code>
     * @return string
     */
    public function getDirectXSupport()
    {
        return isset($this->direct_x_support) ? $this->direct_x_support : '';
    }

    public function hasDirectXSupport()
    {
        return isset($this->direct_x_support);
    }

    public function clearDirectXSupport()
    {
        unset($this->direct_x_support);
    }

    /**
     * Generated from protobuf field <code>optional string direct_x_support = 48;</code>
     * @param string $var
     * @return $this
     */
    public function setDirectXSupport($var)
    {
        GPBUtil::checkString($var, True);
        $this->direct_x_support = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string open_gl_support = 49;</code>
     * @return string
     */
    public function getOpenGlSupport()
    {
        return isset($this->open_gl_support) ? $this->open_gl_support : '';
    }

    public function hasOpenGlSupport()
    {
        return isset($this->open_gl_support);
    }

    public function clearOpenGlSupport()
    {
        unset($this->open_gl_support);
    }

    /**
     * Generated from protobuf field <code>optional string open_gl_support = 49;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenGlSupport($var)
    {
        GPBUtil::checkString($var, True);
        $this->open_gl_support = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string open_cl_support = 50;</code>
     * @return string
     */
    public function getOpenClSupport()
    {
        return isset($this->open_cl_support) ? $this->open_cl_support : '';
    }

    public function hasOpenClSupport()
    {
        return isset($this->open_cl_support);
    }

    public function clearOpenClSupport()
    {
        unset($this->open_cl_support);
    }

    /**
     * Generated from protobuf field <code>optional string open_cl_support = 50;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenClSupport($var)
    {
        GPBUtil::checkString($var, True);
        $this->open_cl_support = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string vulkan_support = 51;</code>
     * @return string
     */
    public function getVulkanSupport()
    {
        return isset($this->vulkan_support) ? $this->vulkan_support : '';
    }

    public function hasVulkanSupport()
    {
        return isset($this->vulkan_support);
    }

    public function clearVulkanSupport()
    {
        unset($this->vulkan_support);
    }

    /**
     * Generated from protobuf field <code>optional string vulkan_support = 51;</code>
     * @param string $var
     * @return $this
     */
    public function setVulkanSupport($var)
    {
        GPBUtil::checkString($var, True);
        $this->vulkan_support = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string vram_type = 52;</code>
     * @return string
     */
    public function getVramType()
    {
        return isset($this->vram_type) ? $this->vram_type : '';
    }

    public function hasVramType()
    {
        return isset($this->vram_type);
    }

    public function clearVramType()
    {
        unset($this->vram_type);
    }

    /**
     * Generated from protobuf field <code>optional string vram_type = 52;</code>
     * @param string $var
     * @return $this
     */
    public function setVramType($var)
    {
        GPBUtil::checkString($var, True);
        $this->vram_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 render_output_unit_count = 53;</code>
     * @return int
     */
    public function getRenderOutputUnitCount()
    {
        return isset($this->render_output_unit_count) ? $this->render_output_unit_count : 0;
    }

    public function hasRenderOutputUnitCount()
    {
        return isset($this->render_output_unit_count);
    }

    public function clearRenderOutputUnitCount()
    {
        unset($this->render_output_unit_count);
    }

    /**
     * Generated from protobuf field <code>optional uint32 render_output_unit_count = 53;</code>
     * @param int $var
     * @return $this
     */
    public function setRenderOutputUnitCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->render_output_unit_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 texture_mapping_unit_count = 54;</code>
     * @return int
     */
    public function getTextureMappingUnitCount()
    {
        return isset($this->texture_mapping_unit_count) ? $this->texture_mapping_unit_count : 0;
    }

    public function hasTextureMappingUnitCount()
    {
        return isset($this->texture_mapping_unit_count);
    }

    public function clearTextureMappingUnitCount()
    {
        unset($this->texture_mapping_unit_count);
    }

    /**
     * Generated from protobuf field <code>optional uint32 texture_mapping_unit_count = 54;</code>
     * @param int $var
     * @return $this
     */
    public function setTextureMappingUnitCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->texture_mapping_unit_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string gpu_model = 55;</code>
     * @return string
     */
    public function getGpuModel()
    {
        return isset($this->gpu_model) ? $this->gpu_model : '';
    }

    public function hasGpuModel()
    {
        return isset($this->gpu_model);
    }

    public function clearGpuModel()
    {
        unset($this->gpu_model);
    }

    /**
     * Generated from protobuf field <code>optional string gpu_model = 55;</code>
     * @param string $var
     * @return $this
     */
    public function setGpuModel($var)
    {
        GPBUtil::checkString($var, True);
        $this->gpu_model = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string hlsl_shader_model = 56;</code>
     * @return string
     */
    public function getHlslShaderModel()
    {
        return isset($this->hlsl_shader_model) ? $this->hlsl_shader_model : '';
    }

    public function hasHlslShaderModel()
    {
        return isset($this->hlsl_shader_model);
    }

    public function clearHlslShaderModel()
    {
        unset($this->hlsl_shader_model);
    }

    /**
     * Generated from protobuf field <code>optional string hlsl_shader_model = 56;</code>
     * @param string $var
     * @return $this
     */
    public function setHlslShaderModel($var)
    {
        GPBUtil::checkString($var, True);
        $this->hlsl_shader_model = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string gpu_boost_frequency = 57;</code>
     * @return string
     */
    public function getGpuBoostFrequency()
    {
        return isset($this->gpu_boost_frequency) ? $this->gpu_boost_frequency : '';
    }

    public function hasGpuBoostFrequency()
    {
        return isset($this->gpu_boost_frequency);
    }

    public function clearGpuBoostFrequency()
    {
        unset($this->gpu_boost_frequency);
    }

    /**
     * Generated from protobuf field <code>optional string gpu_boost_frequency = 57;</code>
     * @param string $var
     * @return $this
     */
    public function setGpuBoostFrequency($var)
    {
        GPBUtil::checkString($var, True);
        $this->gpu_boost_frequency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 ray_tracing_cores = 58;</code>
     * @return int
     */
    public function getRayTracingCores()
    {
        return isset($this->ray_tracing_cores) ? $this->ray_tracing_cores : 0;
    }

    public function hasRayTracingCores()
    {
        return isset($this->ray_tracing_cores);
    }

    public function clearRayTracingCores()
    {
        unset($this->ray_tracing_cores);
    }

    /**
     * Generated from protobuf field <code>optional uint32 ray_tracing_cores = 58;</code>
     * @param int $var
     * @return $this
     */
    public function setRayTracingCores($var)
    {
        GPBUtil::checkUint32($var);
        $this->ray_tracing_cores = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 tensor_cores = 59;</code>
     * @return int
     */
    public function getTensorCores()
    {
        return isset($this->tensor_cores) ? $this->tensor_cores : 0;
    }

    public function hasTensorCores()
    {
        return isset($this->tensor_cores);
    }

    public function clearTensorCores()
    {
        unset($this->tensor_cores);
    }

    /**
     * Generated from protobuf field <code>optional uint32 tensor_cores = 59;</code>
     * @param int $var
     * @return $this
     */
    public function setTensorCores($var)
    {
        GPBUtil::checkUint32($var);
        $this->tensor_cores = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string hardware_accelerated_encoding = 60;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHardwareAcceleratedEncoding()
    {
        return $this->hardware_accelerated_encoding;
    }

    /**
     * Generated from protobuf field <code>repeated string hardware_accelerated_encoding = 60;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHardwareAcceleratedEncoding($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->hardware_accelerated_encoding = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string hardware_accelerated_decoding = 61;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHardwareAcceleratedDecoding()
    {
        return $this->hardware_accelerated_decoding;
    }

    /**
     * Generated from protobuf field <code>repeated string hardware_accelerated_decoding = 61;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHardwareAcceleratedDecoding($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->hardware_accelerated_decoding = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string module_count = 62;</code>
     * @return string
     */
    public function getModuleCount()
    {
        return isset($this->module_count) ? $this->module_count : '';
    }

    public function hasModuleCount()
    {
        return isset($this->module_count);
    }

    public function clearModuleCount()
    {
        unset($this->module_count);
    }

    /**
     * Generated from protobuf field <code>optional string module_count = 62;</code>
     * @param string $var
     * @return $this
     */
    public function setModuleCount($var)
    {
        GPBUtil::checkString($var, True);
        $this->module_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 pixel_shaders = 63;</code>
     * @return int
     */
    public function getPixelShaders()
    {
        return isset($this->pixel_shaders) ? $this->pixel_shaders : 0;
    }

    public function hasPixelShaders()
    {
        return isset($this->pixel_shaders);
    }

    public function clearPixelShaders()
    {
        unset($this->pixel_shaders);
    }

    /**
     * Generated from protobuf field <code>optional uint32 pixel_shaders = 63;</code>
     * @param int $var
     * @return $this
     */
    public function setPixelShaders($var)
    {
        GPBUtil::checkUint32($var);
        $this->pixel_shaders = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string max_displays = 64;</code>
     * @return string
     */
    public function getMaxDisplays()
    {
        return isset($this->max_displays) ? $this->max_displays : '';
    }

    public function hasMaxDisplays()
    {
        return isset($this->max_displays);
    }

    public function clearMaxDisplays()
    {
        unset($this->max_displays);
    }

    /**
     * Generated from protobuf field <code>optional string max_displays = 64;</code>
     * @param string $var
     * @return $this
     */
    public function setMaxDisplays($var)
    {
        GPBUtil::checkString($var, True);
        $this->max_displays = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string crossfire_support = 65;</code>
     * @return string
     */
    public function getCrossfireSupport()
    {
        return isset($this->crossfire_support) ? $this->crossfire_support : '';
    }

    public function hasCrossfireSupport()
    {
        return isset($this->crossfire_support);
    }

    public function clearCrossfireSupport()
    {
        unset($this->crossfire_support);
    }

    /**
     * Generated from protobuf field <code>optional string crossfire_support = 65;</code>
     * @param string $var
     * @return $this
     */
    public function setCrossfireSupport($var)
    {
        GPBUtil::checkString($var, True);
        $this->crossfire_support = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string free_sync_support = 66;</code>
     * @return string
     */
    public function getFreeSyncSupport()
    {
        return isset($this->free_sync_support) ? $this->free_sync_support : '';
    }

    public function hasFreeSyncSupport()
    {
        return isset($this->free_sync_support);
    }

    public function clearFreeSyncSupport()
    {
        unset($this->free_sync_support);
    }

    /**
     * Generated from protobuf field <code>optional string free_sync_support = 66;</code>
     * @param string $var
     * @return $this
     */
    public function setFreeSyncSupport($var)
    {
        GPBUtil::checkString($var, True);
        $this->free_sync_support = $var;

        return $this;
    }

}

