<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

namespace SpecDb\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * /v1/protobuf/apu_architecture/{query}
 *
 * Generated from protobuf message <code>specdb.query.ApuArchitecture</code>
 */
class ApuArchitecture extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .specdb.query.Section sections = 1;</code>
     */
    private $sections;
    /**
     * Generated from protobuf field <code>string lithography = 2;</code>
     */
    protected $lithography = '';
    /**
     * Generated from protobuf field <code>string release_date = 3;</code>
     */
    protected $release_date = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\SpecDb\Query\Section>|\Google\Protobuf\Internal\RepeatedField $sections
     *     @type string $lithography
     *     @type string $release_date
     * }
     */
    public function __construct($data = NULL) {
        \SpecDb\Metadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .specdb.query.Section sections = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSections()
    {
        return $this->sections;
    }

    /**
     * Generated from protobuf field <code>repeated .specdb.query.Section sections = 1;</code>
     * @param array<\SpecDb\Query\Section>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSections($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \SpecDb\Query\Section::class);
        $this->sections = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string lithography = 2;</code>
     * @return string
     */
    public function getLithography()
    {
        return $this->lithography;
    }

    /**
     * Generated from protobuf field <code>string lithography = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLithography($var)
    {
        GPBUtil::checkString($var, True);
        $this->lithography = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string release_date = 3;</code>
     * @return string
     */
    public function getReleaseDate()
    {
        return $this->release_date;
    }

    /**
     * Generated from protobuf field <code>string release_date = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setReleaseDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->release_date = $var;

        return $this;
    }

}

