<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

namespace SpecDb\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>specdb.query.Extra</code>
 */
class Extra extends \Google\Protobuf\Internal\Message
{
    /**
     * Optional namespace for typed extras (e.g. "benchmarks.v1").
     *
     * Generated from protobuf field <code>string namespace = 1;</code>
     */
    protected $namespace = '';
    /**
     * For lists of numeric metrics (cannot be inside a oneof)
     *
     * Generated from protobuf field <code>repeated double double_list = 17;</code>
     */
    private $double_list;
    /**
     * Version/metadata to help with concurrency and auditing.
     *
     * Generated from protobuf field <code>uint64 version = 20;</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 21;</code>
     */
    protected $updated_at = null;
    /**
     * Generated from protobuf field <code>string source = 22;</code>
     */
    protected $source = '';
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $namespace
     *           Optional namespace for typed extras (e.g. "benchmarks.v1").
     *     @type string $string_value
     *     @type int|string $int_value
     *     @type float $double_value
     *     @type bool $bool_value
     *     @type \Google\Protobuf\Struct $object_value
     *     @type string $bytes_value
     *     @type array<float>|\Google\Protobuf\Internal\RepeatedField $double_list
     *           For lists of numeric metrics (cannot be inside a oneof)
     *     @type int|string $version
     *           Version/metadata to help with concurrency and auditing.
     *     @type \Google\Protobuf\Timestamp $updated_at
     *     @type string $source
     * }
     */
    public function __construct($data = NULL) {
        \SpecDb\Metadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Optional namespace for typed extras (e.g. "benchmarks.v1").
     *
     * Generated from protobuf field <code>string namespace = 1;</code>
     * @return string
     */
    public function getNamespace()
    {
        return $this->namespace;
    }

    /**
     * Optional namespace for typed extras (e.g. "benchmarks.v1").
     *
     * Generated from protobuf field <code>string namespace = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setNamespace($var)
    {
        GPBUtil::checkString($var, True);
        $this->namespace = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string string_value = 10;</code>
     * @return string
     */
    public function getStringValue()
    {
        return $this->readOneof(10);
    }

    public function hasStringValue()
    {
        return $this->hasOneof(10);
    }

    /**
     * Generated from protobuf field <code>string string_value = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setStringValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 int_value = 11;</code>
     * @return int|string
     */
    public function getIntValue()
    {
        return $this->readOneof(11);
    }

    public function hasIntValue()
    {
        return $this->hasOneof(11);
    }

    /**
     * Generated from protobuf field <code>int64 int_value = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIntValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>double double_value = 12;</code>
     * @return float
     */
    public function getDoubleValue()
    {
        return $this->readOneof(12);
    }

    public function hasDoubleValue()
    {
        return $this->hasOneof(12);
    }

    /**
     * Generated from protobuf field <code>double double_value = 12;</code>
     * @param float $var
     * @return $this
     */
    public function setDoubleValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool bool_value = 13;</code>
     * @return bool
     */
    public function getBoolValue()
    {
        return $this->readOneof(13);
    }

    public function hasBoolValue()
    {
        return $this->hasOneof(13);
    }

    /**
     * Generated from protobuf field <code>bool bool_value = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setBoolValue($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(13, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct object_value = 15;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getObjectValue()
    {
        return $this->readOneof(15);
    }

    public function hasObjectValue()
    {
        return $this->hasOneof(15);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct object_value = 15;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setObjectValue($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->writeOneof(15, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes bytes_value = 16;</code>
     * @return string
     */
    public function getBytesValue()
    {
        return $this->readOneof(16);
    }

    public function hasBytesValue()
    {
        return $this->hasOneof(16);
    }

    /**
     * Generated from protobuf field <code>bytes bytes_value = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setBytesValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(16, $var);

        return $this;
    }

    /**
     * For lists of numeric metrics (cannot be inside a oneof)
     *
     * Generated from protobuf field <code>repeated double double_list = 17;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDoubleList()
    {
        return $this->double_list;
    }

    /**
     * For lists of numeric metrics (cannot be inside a oneof)
     *
     * Generated from protobuf field <code>repeated double double_list = 17;</code>
     * @param array<float>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDoubleList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::DOUBLE);
        $this->double_list = $arr;

        return $this;
    }

    /**
     * Version/metadata to help with concurrency and auditing.
     *
     * Generated from protobuf field <code>uint64 version = 20;</code>
     * @return int|string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Version/metadata to help with concurrency and auditing.
     *
     * Generated from protobuf field <code>uint64 version = 20;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkUint64($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 21;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    public function hasUpdatedAt()
    {
        return isset($this->updated_at);
    }

    public function clearUpdatedAt()
    {
        unset($this->updated_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 21;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string source = 22;</code>
     * @return string
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * Generated from protobuf field <code>string source = 22;</code>
     * @param string $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->source = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

