<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

namespace SpecDb\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * /v1/protobuf/generic_container/{query}
 *
 * Generated from protobuf message <code>specdb.query.GenericContainer</code>
 */
class GenericContainer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string top_header = 1;</code>
     */
    protected $top_header = '';
    /**
     * Generated from protobuf field <code>repeated .specdb.query.Section sections = 2;</code>
     */
    private $sections;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $top_header
     *     @type array<\SpecDb\Query\Section>|\Google\Protobuf\Internal\RepeatedField $sections
     * }
     */
    public function __construct($data = NULL) {
        \SpecDb\Metadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string top_header = 1;</code>
     * @return string
     */
    public function getTopHeader()
    {
        return $this->top_header;
    }

    /**
     * Generated from protobuf field <code>string top_header = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTopHeader($var)
    {
        GPBUtil::checkString($var, True);
        $this->top_header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .specdb.query.Section sections = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSections()
    {
        return $this->sections;
    }

    /**
     * Generated from protobuf field <code>repeated .specdb.query.Section sections = 2;</code>
     * @param array<\SpecDb\Query\Section>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSections($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \SpecDb\Query\Section::class);
        $this->sections = $arr;

        return $this;
    }

}

