<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

namespace SpecDb\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>specdb.query.GetExtrasResponse</code>
 */
class GetExtrasResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Map from section_header -> map<key, Extra>
     *
     * Generated from protobuf field <code>map<string, .specdb.query.SectionExtras> extras_by_section = 1;</code>
     */
    private $extras_by_section;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $extras_by_section
     *           Map from section_header -> map<key, Extra>
     * }
     */
    public function __construct($data = NULL) {
        \SpecDb\Metadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Map from section_header -> map<key, Extra>
     *
     * Generated from protobuf field <code>map<string, .specdb.query.SectionExtras> extras_by_section = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getExtrasBySection()
    {
        return $this->extras_by_section;
    }

    /**
     * Map from section_header -> map<key, Extra>
     *
     * Generated from protobuf field <code>map<string, .specdb.query.SectionExtras> extras_by_section = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setExtrasBySection($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \SpecDb\Query\SectionExtras::class);
        $this->extras_by_section = $arr;

        return $this;
    }

}

