<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

namespace SpecDb\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Retrieve extras for a spec (optionally for a specific section)
 *
 * Generated from protobuf message <code>specdb.query.GetExtrasRequest</code>
 */
class GetExtrasRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string spec_name = 1;</code>
     */
    protected $spec_name = '';
    /**
     * optional: if empty, return extras for all sections for this spec
     *
     * Generated from protobuf field <code>string section_header = 2;</code>
     */
    protected $section_header = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $spec_name
     *     @type string $section_header
     *           optional: if empty, return extras for all sections for this spec
     * }
     */
    public function __construct($data = NULL) {
        \SpecDb\Metadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string spec_name = 1;</code>
     * @return string
     */
    public function getSpecName()
    {
        return $this->spec_name;
    }

    /**
     * Generated from protobuf field <code>string spec_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSpecName($var)
    {
        GPBUtil::checkString($var, True);
        $this->spec_name = $var;

        return $this;
    }

    /**
     * optional: if empty, return extras for all sections for this spec
     *
     * Generated from protobuf field <code>string section_header = 2;</code>
     * @return string
     */
    public function getSectionHeader()
    {
        return $this->section_header;
    }

    /**
     * optional: if empty, return extras for all sections for this spec
     *
     * Generated from protobuf field <code>string section_header = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSectionHeader($var)
    {
        GPBUtil::checkString($var, True);
        $this->section_header = $var;

        return $this;
    }

}

