<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

namespace SpecDb\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * /v1/protobuf/graphics_architecture/{query}
 *
 * Generated from protobuf message <code>specdb.query.GraphicsArchitecture</code>
 */
class GraphicsArchitecture extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .specdb.query.Section sections = 1;</code>
     */
    private $sections;
    /**
     * Generated from protobuf field <code>string lithography = 2;</code>
     */
    protected $lithography = '';
    /**
     * Generated from protobuf field <code>string release_date = 3;</code>
     */
    protected $release_date = '';
    /**
     * Generated from protobuf field <code>optional string direct_x_support = 4;</code>
     */
    protected $direct_x_support = null;
    /**
     * Generated from protobuf field <code>optional string vulkan_support = 5;</code>
     */
    protected $vulkan_support = null;
    /**
     * Generated from protobuf field <code>optional string manufacturer = 6;</code>
     */
    protected $manufacturer = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\SpecDb\Query\Section>|\Google\Protobuf\Internal\RepeatedField $sections
     *     @type string $lithography
     *     @type string $release_date
     *     @type string $direct_x_support
     *     @type string $vulkan_support
     *     @type string $manufacturer
     * }
     */
    public function __construct($data = NULL) {
        \SpecDb\Metadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .specdb.query.Section sections = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSections()
    {
        return $this->sections;
    }

    /**
     * Generated from protobuf field <code>repeated .specdb.query.Section sections = 1;</code>
     * @param array<\SpecDb\Query\Section>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSections($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \SpecDb\Query\Section::class);
        $this->sections = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string lithography = 2;</code>
     * @return string
     */
    public function getLithography()
    {
        return $this->lithography;
    }

    /**
     * Generated from protobuf field <code>string lithography = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLithography($var)
    {
        GPBUtil::checkString($var, True);
        $this->lithography = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string release_date = 3;</code>
     * @return string
     */
    public function getReleaseDate()
    {
        return $this->release_date;
    }

    /**
     * Generated from protobuf field <code>string release_date = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setReleaseDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->release_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string direct_x_support = 4;</code>
     * @return string
     */
    public function getDirectXSupport()
    {
        return isset($this->direct_x_support) ? $this->direct_x_support : '';
    }

    public function hasDirectXSupport()
    {
        return isset($this->direct_x_support);
    }

    public function clearDirectXSupport()
    {
        unset($this->direct_x_support);
    }

    /**
     * Generated from protobuf field <code>optional string direct_x_support = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDirectXSupport($var)
    {
        GPBUtil::checkString($var, True);
        $this->direct_x_support = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string vulkan_support = 5;</code>
     * @return string
     */
    public function getVulkanSupport()
    {
        return isset($this->vulkan_support) ? $this->vulkan_support : '';
    }

    public function hasVulkanSupport()
    {
        return isset($this->vulkan_support);
    }

    public function clearVulkanSupport()
    {
        unset($this->vulkan_support);
    }

    /**
     * Generated from protobuf field <code>optional string vulkan_support = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setVulkanSupport($var)
    {
        GPBUtil::checkString($var, True);
        $this->vulkan_support = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string manufacturer = 6;</code>
     * @return string
     */
    public function getManufacturer()
    {
        return isset($this->manufacturer) ? $this->manufacturer : '';
    }

    public function hasManufacturer()
    {
        return isset($this->manufacturer);
    }

    public function clearManufacturer()
    {
        unset($this->manufacturer);
    }

    /**
     * Generated from protobuf field <code>optional string manufacturer = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setManufacturer($var)
    {
        GPBUtil::checkString($var, True);
        $this->manufacturer = $var;

        return $this;
    }

}

