<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

namespace SpecDb\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * /v1/protobuf/graphics_card/{query}
 *
 * Generated from protobuf message <code>specdb.query.GraphicsCard</code>
 */
class GraphicsCard extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string vram_capacity = 1;</code>
     */
    protected $vram_capacity = '';
    /**
     * Generated from protobuf field <code>uint32 shader_processor_count = 2;</code>
     */
    protected $shader_processor_count = 0;
    /**
     * Generated from protobuf field <code>string gpu_base_frequency = 3;</code>
     */
    protected $gpu_base_frequency = '';
    /**
     * Generated from protobuf field <code>optional string manufacturer = 4;</code>
     */
    protected $manufacturer = null;
    /**
     * Generated from protobuf field <code>optional string vendor = 5;</code>
     */
    protected $vendor = null;
    /**
     * Generated from protobuf field <code>repeated string market = 6;</code>
     */
    private $market;
    /**
     * Generated from protobuf field <code>optional string architecture = 7;</code>
     */
    protected $architecture = null;
    /**
     * Generated from protobuf field <code>optional string lithography = 8;</code>
     */
    protected $lithography = null;
    /**
     * Generated from protobuf field <code>optional string release_date = 9;</code>
     */
    protected $release_date = null;
    /**
     * Generated from protobuf field <code>optional string direct_x_support = 10;</code>
     */
    protected $direct_x_support = null;
    /**
     * Generated from protobuf field <code>optional string open_gl_support = 11;</code>
     */
    protected $open_gl_support = null;
    /**
     * Generated from protobuf field <code>optional string open_cl_support = 12;</code>
     */
    protected $open_cl_support = null;
    /**
     * Generated from protobuf field <code>optional string vulkan_support = 13;</code>
     */
    protected $vulkan_support = null;
    /**
     * Generated from protobuf field <code>optional string vram_frequency = 14;</code>
     */
    protected $vram_frequency = null;
    /**
     * Generated from protobuf field <code>optional string vram_type = 15;</code>
     */
    protected $vram_type = null;
    /**
     * Generated from protobuf field <code>optional string vram_bandwidth = 16;</code>
     */
    protected $vram_bandwidth = null;
    /**
     * Generated from protobuf field <code>optional string vram_bus_width = 17;</code>
     */
    protected $vram_bus_width = null;
    /**
     * Generated from protobuf field <code>optional uint32 render_output_unit_count = 18;</code>
     */
    protected $render_output_unit_count = null;
    /**
     * Generated from protobuf field <code>optional uint32 texture_mapping_unit_count = 19;</code>
     */
    protected $texture_mapping_unit_count = null;
    /**
     * Generated from protobuf field <code>optional string die_size = 20;</code>
     */
    protected $die_size = null;
    /**
     * Generated from protobuf field <code>optional string tdp = 21;</code>
     */
    protected $tdp = null;
    /**
     * Generated from protobuf field <code>optional string gpu = 22;</code>
     */
    protected $gpu = null;
    /**
     * Generated from protobuf field <code>optional string gpu_variant = 23;</code>
     */
    protected $gpu_variant = null;
    /**
     * Generated from protobuf field <code>optional string gpu_model = 24;</code>
     */
    protected $gpu_model = null;
    /**
     * Generated from protobuf field <code>optional string hlsl_shader_model = 25;</code>
     */
    protected $hlsl_shader_model = null;
    /**
     * Generated from protobuf field <code>optional string gpu_boost_frequency = 26;</code>
     */
    protected $gpu_boost_frequency = null;
    /**
     * Generated from protobuf field <code>optional string fp32_compute = 27;</code>
     */
    protected $fp32_compute = null;
    /**
     * Generated from protobuf field <code>optional string fp64_compute = 28;</code>
     */
    protected $fp64_compute = null;
    /**
     * Generated from protobuf field <code>optional string slot_width = 29;</code>
     */
    protected $slot_width = null;
    /**
     * Generated from protobuf field <code>repeated string outputs = 30;</code>
     */
    private $outputs;
    /**
     * Generated from protobuf field <code>repeated string power_connectors = 31;</code>
     */
    private $power_connectors;
    /**
     * Generated from protobuf field <code>optional string length = 32;</code>
     */
    protected $length = null;
    /**
     * Generated from protobuf field <code>optional string height = 33;</code>
     */
    protected $height = null;
    /**
     * Generated from protobuf field <code>optional string width = 34;</code>
     */
    protected $width = null;
    /**
     * Generated from protobuf field <code>optional uint32 ray_tracing_cores = 35;</code>
     */
    protected $ray_tracing_cores = null;
    /**
     * Generated from protobuf field <code>optional uint32 tensor_cores = 36;</code>
     */
    protected $tensor_cores = null;
    /**
     * Generated from protobuf field <code>repeated string hardware_accelerated_encoding = 37;</code>
     */
    private $hardware_accelerated_encoding;
    /**
     * Generated from protobuf field <code>repeated string hardware_accelerated_decoding = 38;</code>
     */
    private $hardware_accelerated_decoding;
    /**
     * Generated from protobuf field <code>optional string module_count = 39;</code>
     */
    protected $module_count = null;
    /**
     * Generated from protobuf field <code>optional uint32 pixel_shaders = 40;</code>
     */
    protected $pixel_shaders = null;
    /**
     * Generated from protobuf field <code>optional string maximum_vram_capacity = 41;</code>
     */
    protected $maximum_vram_capacity = null;
    /**
     * Generated from protobuf field <code>optional string max_displays = 42;</code>
     */
    protected $max_displays = null;
    /**
     * Generated from protobuf field <code>optional string crossfire_support = 43;</code>
     */
    protected $crossfire_support = null;
    /**
     * Generated from protobuf field <code>optional string free_sync_support = 44;</code>
     */
    protected $free_sync_support = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $vram_capacity
     *     @type int $shader_processor_count
     *     @type string $gpu_base_frequency
     *     @type string $manufacturer
     *     @type string $vendor
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $market
     *     @type string $architecture
     *     @type string $lithography
     *     @type string $release_date
     *     @type string $direct_x_support
     *     @type string $open_gl_support
     *     @type string $open_cl_support
     *     @type string $vulkan_support
     *     @type string $vram_frequency
     *     @type string $vram_type
     *     @type string $vram_bandwidth
     *     @type string $vram_bus_width
     *     @type int $render_output_unit_count
     *     @type int $texture_mapping_unit_count
     *     @type string $die_size
     *     @type string $tdp
     *     @type string $gpu
     *     @type string $gpu_variant
     *     @type string $gpu_model
     *     @type string $hlsl_shader_model
     *     @type string $gpu_boost_frequency
     *     @type string $fp32_compute
     *     @type string $fp64_compute
     *     @type string $slot_width
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $outputs
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $power_connectors
     *     @type string $length
     *     @type string $height
     *     @type string $width
     *     @type int $ray_tracing_cores
     *     @type int $tensor_cores
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $hardware_accelerated_encoding
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $hardware_accelerated_decoding
     *     @type string $module_count
     *     @type int $pixel_shaders
     *     @type string $maximum_vram_capacity
     *     @type string $max_displays
     *     @type string $crossfire_support
     *     @type string $free_sync_support
     * }
     */
    public function __construct($data = NULL) {
        \SpecDb\Metadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string vram_capacity = 1;</code>
     * @return string
     */
    public function getVramCapacity()
    {
        return $this->vram_capacity;
    }

    /**
     * Generated from protobuf field <code>string vram_capacity = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVramCapacity($var)
    {
        GPBUtil::checkString($var, True);
        $this->vram_capacity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 shader_processor_count = 2;</code>
     * @return int
     */
    public function getShaderProcessorCount()
    {
        return $this->shader_processor_count;
    }

    /**
     * Generated from protobuf field <code>uint32 shader_processor_count = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setShaderProcessorCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->shader_processor_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string gpu_base_frequency = 3;</code>
     * @return string
     */
    public function getGpuBaseFrequency()
    {
        return $this->gpu_base_frequency;
    }

    /**
     * Generated from protobuf field <code>string gpu_base_frequency = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setGpuBaseFrequency($var)
    {
        GPBUtil::checkString($var, True);
        $this->gpu_base_frequency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string manufacturer = 4;</code>
     * @return string
     */
    public function getManufacturer()
    {
        return isset($this->manufacturer) ? $this->manufacturer : '';
    }

    public function hasManufacturer()
    {
        return isset($this->manufacturer);
    }

    public function clearManufacturer()
    {
        unset($this->manufacturer);
    }

    /**
     * Generated from protobuf field <code>optional string manufacturer = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setManufacturer($var)
    {
        GPBUtil::checkString($var, True);
        $this->manufacturer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string vendor = 5;</code>
     * @return string
     */
    public function getVendor()
    {
        return isset($this->vendor) ? $this->vendor : '';
    }

    public function hasVendor()
    {
        return isset($this->vendor);
    }

    public function clearVendor()
    {
        unset($this->vendor);
    }

    /**
     * Generated from protobuf field <code>optional string vendor = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setVendor($var)
    {
        GPBUtil::checkString($var, True);
        $this->vendor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string market = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMarket()
    {
        return $this->market;
    }

    /**
     * Generated from protobuf field <code>repeated string market = 6;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMarket($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->market = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string architecture = 7;</code>
     * @return string
     */
    public function getArchitecture()
    {
        return isset($this->architecture) ? $this->architecture : '';
    }

    public function hasArchitecture()
    {
        return isset($this->architecture);
    }

    public function clearArchitecture()
    {
        unset($this->architecture);
    }

    /**
     * Generated from protobuf field <code>optional string architecture = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setArchitecture($var)
    {
        GPBUtil::checkString($var, True);
        $this->architecture = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string lithography = 8;</code>
     * @return string
     */
    public function getLithography()
    {
        return isset($this->lithography) ? $this->lithography : '';
    }

    public function hasLithography()
    {
        return isset($this->lithography);
    }

    public function clearLithography()
    {
        unset($this->lithography);
    }

    /**
     * Generated from protobuf field <code>optional string lithography = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setLithography($var)
    {
        GPBUtil::checkString($var, True);
        $this->lithography = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string release_date = 9;</code>
     * @return string
     */
    public function getReleaseDate()
    {
        return isset($this->release_date) ? $this->release_date : '';
    }

    public function hasReleaseDate()
    {
        return isset($this->release_date);
    }

    public function clearReleaseDate()
    {
        unset($this->release_date);
    }

    /**
     * Generated from protobuf field <code>optional string release_date = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setReleaseDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->release_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string direct_x_support = 10;</code>
     * @return string
     */
    public function getDirectXSupport()
    {
        return isset($this->direct_x_support) ? $this->direct_x_support : '';
    }

    public function hasDirectXSupport()
    {
        return isset($this->direct_x_support);
    }

    public function clearDirectXSupport()
    {
        unset($this->direct_x_support);
    }

    /**
     * Generated from protobuf field <code>optional string direct_x_support = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setDirectXSupport($var)
    {
        GPBUtil::checkString($var, True);
        $this->direct_x_support = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string open_gl_support = 11;</code>
     * @return string
     */
    public function getOpenGlSupport()
    {
        return isset($this->open_gl_support) ? $this->open_gl_support : '';
    }

    public function hasOpenGlSupport()
    {
        return isset($this->open_gl_support);
    }

    public function clearOpenGlSupport()
    {
        unset($this->open_gl_support);
    }

    /**
     * Generated from protobuf field <code>optional string open_gl_support = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenGlSupport($var)
    {
        GPBUtil::checkString($var, True);
        $this->open_gl_support = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string open_cl_support = 12;</code>
     * @return string
     */
    public function getOpenClSupport()
    {
        return isset($this->open_cl_support) ? $this->open_cl_support : '';
    }

    public function hasOpenClSupport()
    {
        return isset($this->open_cl_support);
    }

    public function clearOpenClSupport()
    {
        unset($this->open_cl_support);
    }

    /**
     * Generated from protobuf field <code>optional string open_cl_support = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenClSupport($var)
    {
        GPBUtil::checkString($var, True);
        $this->open_cl_support = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string vulkan_support = 13;</code>
     * @return string
     */
    public function getVulkanSupport()
    {
        return isset($this->vulkan_support) ? $this->vulkan_support : '';
    }

    public function hasVulkanSupport()
    {
        return isset($this->vulkan_support);
    }

    public function clearVulkanSupport()
    {
        unset($this->vulkan_support);
    }

    /**
     * Generated from protobuf field <code>optional string vulkan_support = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setVulkanSupport($var)
    {
        GPBUtil::checkString($var, True);
        $this->vulkan_support = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string vram_frequency = 14;</code>
     * @return string
     */
    public function getVramFrequency()
    {
        return isset($this->vram_frequency) ? $this->vram_frequency : '';
    }

    public function hasVramFrequency()
    {
        return isset($this->vram_frequency);
    }

    public function clearVramFrequency()
    {
        unset($this->vram_frequency);
    }

    /**
     * Generated from protobuf field <code>optional string vram_frequency = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setVramFrequency($var)
    {
        GPBUtil::checkString($var, True);
        $this->vram_frequency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string vram_type = 15;</code>
     * @return string
     */
    public function getVramType()
    {
        return isset($this->vram_type) ? $this->vram_type : '';
    }

    public function hasVramType()
    {
        return isset($this->vram_type);
    }

    public function clearVramType()
    {
        unset($this->vram_type);
    }

    /**
     * Generated from protobuf field <code>optional string vram_type = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setVramType($var)
    {
        GPBUtil::checkString($var, True);
        $this->vram_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string vram_bandwidth = 16;</code>
     * @return string
     */
    public function getVramBandwidth()
    {
        return isset($this->vram_bandwidth) ? $this->vram_bandwidth : '';
    }

    public function hasVramBandwidth()
    {
        return isset($this->vram_bandwidth);
    }

    public function clearVramBandwidth()
    {
        unset($this->vram_bandwidth);
    }

    /**
     * Generated from protobuf field <code>optional string vram_bandwidth = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setVramBandwidth($var)
    {
        GPBUtil::checkString($var, True);
        $this->vram_bandwidth = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string vram_bus_width = 17;</code>
     * @return string
     */
    public function getVramBusWidth()
    {
        return isset($this->vram_bus_width) ? $this->vram_bus_width : '';
    }

    public function hasVramBusWidth()
    {
        return isset($this->vram_bus_width);
    }

    public function clearVramBusWidth()
    {
        unset($this->vram_bus_width);
    }

    /**
     * Generated from protobuf field <code>optional string vram_bus_width = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setVramBusWidth($var)
    {
        GPBUtil::checkString($var, True);
        $this->vram_bus_width = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 render_output_unit_count = 18;</code>
     * @return int
     */
    public function getRenderOutputUnitCount()
    {
        return isset($this->render_output_unit_count) ? $this->render_output_unit_count : 0;
    }

    public function hasRenderOutputUnitCount()
    {
        return isset($this->render_output_unit_count);
    }

    public function clearRenderOutputUnitCount()
    {
        unset($this->render_output_unit_count);
    }

    /**
     * Generated from protobuf field <code>optional uint32 render_output_unit_count = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setRenderOutputUnitCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->render_output_unit_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 texture_mapping_unit_count = 19;</code>
     * @return int
     */
    public function getTextureMappingUnitCount()
    {
        return isset($this->texture_mapping_unit_count) ? $this->texture_mapping_unit_count : 0;
    }

    public function hasTextureMappingUnitCount()
    {
        return isset($this->texture_mapping_unit_count);
    }

    public function clearTextureMappingUnitCount()
    {
        unset($this->texture_mapping_unit_count);
    }

    /**
     * Generated from protobuf field <code>optional uint32 texture_mapping_unit_count = 19;</code>
     * @param int $var
     * @return $this
     */
    public function setTextureMappingUnitCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->texture_mapping_unit_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string die_size = 20;</code>
     * @return string
     */
    public function getDieSize()
    {
        return isset($this->die_size) ? $this->die_size : '';
    }

    public function hasDieSize()
    {
        return isset($this->die_size);
    }

    public function clearDieSize()
    {
        unset($this->die_size);
    }

    /**
     * Generated from protobuf field <code>optional string die_size = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setDieSize($var)
    {
        GPBUtil::checkString($var, True);
        $this->die_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string tdp = 21;</code>
     * @return string
     */
    public function getTdp()
    {
        return isset($this->tdp) ? $this->tdp : '';
    }

    public function hasTdp()
    {
        return isset($this->tdp);
    }

    public function clearTdp()
    {
        unset($this->tdp);
    }

    /**
     * Generated from protobuf field <code>optional string tdp = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setTdp($var)
    {
        GPBUtil::checkString($var, True);
        $this->tdp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string gpu = 22;</code>
     * @return string
     */
    public function getGpu()
    {
        return isset($this->gpu) ? $this->gpu : '';
    }

    public function hasGpu()
    {
        return isset($this->gpu);
    }

    public function clearGpu()
    {
        unset($this->gpu);
    }

    /**
     * Generated from protobuf field <code>optional string gpu = 22;</code>
     * @param string $var
     * @return $this
     */
    public function setGpu($var)
    {
        GPBUtil::checkString($var, True);
        $this->gpu = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string gpu_variant = 23;</code>
     * @return string
     */
    public function getGpuVariant()
    {
        return isset($this->gpu_variant) ? $this->gpu_variant : '';
    }

    public function hasGpuVariant()
    {
        return isset($this->gpu_variant);
    }

    public function clearGpuVariant()
    {
        unset($this->gpu_variant);
    }

    /**
     * Generated from protobuf field <code>optional string gpu_variant = 23;</code>
     * @param string $var
     * @return $this
     */
    public function setGpuVariant($var)
    {
        GPBUtil::checkString($var, True);
        $this->gpu_variant = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string gpu_model = 24;</code>
     * @return string
     */
    public function getGpuModel()
    {
        return isset($this->gpu_model) ? $this->gpu_model : '';
    }

    public function hasGpuModel()
    {
        return isset($this->gpu_model);
    }

    public function clearGpuModel()
    {
        unset($this->gpu_model);
    }

    /**
     * Generated from protobuf field <code>optional string gpu_model = 24;</code>
     * @param string $var
     * @return $this
     */
    public function setGpuModel($var)
    {
        GPBUtil::checkString($var, True);
        $this->gpu_model = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string hlsl_shader_model = 25;</code>
     * @return string
     */
    public function getHlslShaderModel()
    {
        return isset($this->hlsl_shader_model) ? $this->hlsl_shader_model : '';
    }

    public function hasHlslShaderModel()
    {
        return isset($this->hlsl_shader_model);
    }

    public function clearHlslShaderModel()
    {
        unset($this->hlsl_shader_model);
    }

    /**
     * Generated from protobuf field <code>optional string hlsl_shader_model = 25;</code>
     * @param string $var
     * @return $this
     */
    public function setHlslShaderModel($var)
    {
        GPBUtil::checkString($var, True);
        $this->hlsl_shader_model = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string gpu_boost_frequency = 26;</code>
     * @return string
     */
    public function getGpuBoostFrequency()
    {
        return isset($this->gpu_boost_frequency) ? $this->gpu_boost_frequency : '';
    }

    public function hasGpuBoostFrequency()
    {
        return isset($this->gpu_boost_frequency);
    }

    public function clearGpuBoostFrequency()
    {
        unset($this->gpu_boost_frequency);
    }

    /**
     * Generated from protobuf field <code>optional string gpu_boost_frequency = 26;</code>
     * @param string $var
     * @return $this
     */
    public function setGpuBoostFrequency($var)
    {
        GPBUtil::checkString($var, True);
        $this->gpu_boost_frequency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string fp32_compute = 27;</code>
     * @return string
     */
    public function getFp32Compute()
    {
        return isset($this->fp32_compute) ? $this->fp32_compute : '';
    }

    public function hasFp32Compute()
    {
        return isset($this->fp32_compute);
    }

    public function clearFp32Compute()
    {
        unset($this->fp32_compute);
    }

    /**
     * Generated from protobuf field <code>optional string fp32_compute = 27;</code>
     * @param string $var
     * @return $this
     */
    public function setFp32Compute($var)
    {
        GPBUtil::checkString($var, True);
        $this->fp32_compute = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string fp64_compute = 28;</code>
     * @return string
     */
    public function getFp64Compute()
    {
        return isset($this->fp64_compute) ? $this->fp64_compute : '';
    }

    public function hasFp64Compute()
    {
        return isset($this->fp64_compute);
    }

    public function clearFp64Compute()
    {
        unset($this->fp64_compute);
    }

    /**
     * Generated from protobuf field <code>optional string fp64_compute = 28;</code>
     * @param string $var
     * @return $this
     */
    public function setFp64Compute($var)
    {
        GPBUtil::checkString($var, True);
        $this->fp64_compute = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string slot_width = 29;</code>
     * @return string
     */
    public function getSlotWidth()
    {
        return isset($this->slot_width) ? $this->slot_width : '';
    }

    public function hasSlotWidth()
    {
        return isset($this->slot_width);
    }

    public function clearSlotWidth()
    {
        unset($this->slot_width);
    }

    /**
     * Generated from protobuf field <code>optional string slot_width = 29;</code>
     * @param string $var
     * @return $this
     */
    public function setSlotWidth($var)
    {
        GPBUtil::checkString($var, True);
        $this->slot_width = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string outputs = 30;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOutputs()
    {
        return $this->outputs;
    }

    /**
     * Generated from protobuf field <code>repeated string outputs = 30;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOutputs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->outputs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string power_connectors = 31;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPowerConnectors()
    {
        return $this->power_connectors;
    }

    /**
     * Generated from protobuf field <code>repeated string power_connectors = 31;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPowerConnectors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->power_connectors = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string length = 32;</code>
     * @return string
     */
    public function getLength()
    {
        return isset($this->length) ? $this->length : '';
    }

    public function hasLength()
    {
        return isset($this->length);
    }

    public function clearLength()
    {
        unset($this->length);
    }

    /**
     * Generated from protobuf field <code>optional string length = 32;</code>
     * @param string $var
     * @return $this
     */
    public function setLength($var)
    {
        GPBUtil::checkString($var, True);
        $this->length = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string height = 33;</code>
     * @return string
     */
    public function getHeight()
    {
        return isset($this->height) ? $this->height : '';
    }

    public function hasHeight()
    {
        return isset($this->height);
    }

    public function clearHeight()
    {
        unset($this->height);
    }

    /**
     * Generated from protobuf field <code>optional string height = 33;</code>
     * @param string $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkString($var, True);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string width = 34;</code>
     * @return string
     */
    public function getWidth()
    {
        return isset($this->width) ? $this->width : '';
    }

    public function hasWidth()
    {
        return isset($this->width);
    }

    public function clearWidth()
    {
        unset($this->width);
    }

    /**
     * Generated from protobuf field <code>optional string width = 34;</code>
     * @param string $var
     * @return $this
     */
    public function setWidth($var)
    {
        GPBUtil::checkString($var, True);
        $this->width = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 ray_tracing_cores = 35;</code>
     * @return int
     */
    public function getRayTracingCores()
    {
        return isset($this->ray_tracing_cores) ? $this->ray_tracing_cores : 0;
    }

    public function hasRayTracingCores()
    {
        return isset($this->ray_tracing_cores);
    }

    public function clearRayTracingCores()
    {
        unset($this->ray_tracing_cores);
    }

    /**
     * Generated from protobuf field <code>optional uint32 ray_tracing_cores = 35;</code>
     * @param int $var
     * @return $this
     */
    public function setRayTracingCores($var)
    {
        GPBUtil::checkUint32($var);
        $this->ray_tracing_cores = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 tensor_cores = 36;</code>
     * @return int
     */
    public function getTensorCores()
    {
        return isset($this->tensor_cores) ? $this->tensor_cores : 0;
    }

    public function hasTensorCores()
    {
        return isset($this->tensor_cores);
    }

    public function clearTensorCores()
    {
        unset($this->tensor_cores);
    }

    /**
     * Generated from protobuf field <code>optional uint32 tensor_cores = 36;</code>
     * @param int $var
     * @return $this
     */
    public function setTensorCores($var)
    {
        GPBUtil::checkUint32($var);
        $this->tensor_cores = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string hardware_accelerated_encoding = 37;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHardwareAcceleratedEncoding()
    {
        return $this->hardware_accelerated_encoding;
    }

    /**
     * Generated from protobuf field <code>repeated string hardware_accelerated_encoding = 37;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHardwareAcceleratedEncoding($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->hardware_accelerated_encoding = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string hardware_accelerated_decoding = 38;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHardwareAcceleratedDecoding()
    {
        return $this->hardware_accelerated_decoding;
    }

    /**
     * Generated from protobuf field <code>repeated string hardware_accelerated_decoding = 38;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHardwareAcceleratedDecoding($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->hardware_accelerated_decoding = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string module_count = 39;</code>
     * @return string
     */
    public function getModuleCount()
    {
        return isset($this->module_count) ? $this->module_count : '';
    }

    public function hasModuleCount()
    {
        return isset($this->module_count);
    }

    public function clearModuleCount()
    {
        unset($this->module_count);
    }

    /**
     * Generated from protobuf field <code>optional string module_count = 39;</code>
     * @param string $var
     * @return $this
     */
    public function setModuleCount($var)
    {
        GPBUtil::checkString($var, True);
        $this->module_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 pixel_shaders = 40;</code>
     * @return int
     */
    public function getPixelShaders()
    {
        return isset($this->pixel_shaders) ? $this->pixel_shaders : 0;
    }

    public function hasPixelShaders()
    {
        return isset($this->pixel_shaders);
    }

    public function clearPixelShaders()
    {
        unset($this->pixel_shaders);
    }

    /**
     * Generated from protobuf field <code>optional uint32 pixel_shaders = 40;</code>
     * @param int $var
     * @return $this
     */
    public function setPixelShaders($var)
    {
        GPBUtil::checkUint32($var);
        $this->pixel_shaders = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string maximum_vram_capacity = 41;</code>
     * @return string
     */
    public function getMaximumVramCapacity()
    {
        return isset($this->maximum_vram_capacity) ? $this->maximum_vram_capacity : '';
    }

    public function hasMaximumVramCapacity()
    {
        return isset($this->maximum_vram_capacity);
    }

    public function clearMaximumVramCapacity()
    {
        unset($this->maximum_vram_capacity);
    }

    /**
     * Generated from protobuf field <code>optional string maximum_vram_capacity = 41;</code>
     * @param string $var
     * @return $this
     */
    public function setMaximumVramCapacity($var)
    {
        GPBUtil::checkString($var, True);
        $this->maximum_vram_capacity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string max_displays = 42;</code>
     * @return string
     */
    public function getMaxDisplays()
    {
        return isset($this->max_displays) ? $this->max_displays : '';
    }

    public function hasMaxDisplays()
    {
        return isset($this->max_displays);
    }

    public function clearMaxDisplays()
    {
        unset($this->max_displays);
    }

    /**
     * Generated from protobuf field <code>optional string max_displays = 42;</code>
     * @param string $var
     * @return $this
     */
    public function setMaxDisplays($var)
    {
        GPBUtil::checkString($var, True);
        $this->max_displays = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string crossfire_support = 43;</code>
     * @return string
     */
    public function getCrossfireSupport()
    {
        return isset($this->crossfire_support) ? $this->crossfire_support : '';
    }

    public function hasCrossfireSupport()
    {
        return isset($this->crossfire_support);
    }

    public function clearCrossfireSupport()
    {
        unset($this->crossfire_support);
    }

    /**
     * Generated from protobuf field <code>optional string crossfire_support = 43;</code>
     * @param string $var
     * @return $this
     */
    public function setCrossfireSupport($var)
    {
        GPBUtil::checkString($var, True);
        $this->crossfire_support = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string free_sync_support = 44;</code>
     * @return string
     */
    public function getFreeSyncSupport()
    {
        return isset($this->free_sync_support) ? $this->free_sync_support : '';
    }

    public function hasFreeSyncSupport()
    {
        return isset($this->free_sync_support);
    }

    public function clearFreeSyncSupport()
    {
        unset($this->free_sync_support);
    }

    /**
     * Generated from protobuf field <code>optional string free_sync_support = 44;</code>
     * @param string $var
     * @return $this
     */
    public function setFreeSyncSupport($var)
    {
        GPBUtil::checkString($var, True);
        $this->free_sync_support = $var;

        return $this;
    }

}

