<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

namespace SpecDb\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>specdb.query.RemoveExtraRequest</code>
 */
class RemoveExtraRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string spec_name = 1;</code>
     */
    protected $spec_name = '';
    /**
     * Generated from protobuf field <code>string section_header = 2;</code>
     */
    protected $section_header = '';
    /**
     * Generated from protobuf field <code>string key = 3;</code>
     */
    protected $key = '';
    /**
     * Generated from protobuf field <code>uint64 expected_version = 4;</code>
     */
    protected $expected_version = 0;
    /**
     * Generated from protobuf field <code>string idempotency_key = 5;</code>
     */
    protected $idempotency_key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $spec_name
     *     @type string $section_header
     *     @type string $key
     *     @type int|string $expected_version
     *     @type string $idempotency_key
     * }
     */
    public function __construct($data = NULL) {
        \SpecDb\Metadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string spec_name = 1;</code>
     * @return string
     */
    public function getSpecName()
    {
        return $this->spec_name;
    }

    /**
     * Generated from protobuf field <code>string spec_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSpecName($var)
    {
        GPBUtil::checkString($var, True);
        $this->spec_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string section_header = 2;</code>
     * @return string
     */
    public function getSectionHeader()
    {
        return $this->section_header;
    }

    /**
     * Generated from protobuf field <code>string section_header = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSectionHeader($var)
    {
        GPBUtil::checkString($var, True);
        $this->section_header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key = 3;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>string key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 expected_version = 4;</code>
     * @return int|string
     */
    public function getExpectedVersion()
    {
        return $this->expected_version;
    }

    /**
     * Generated from protobuf field <code>uint64 expected_version = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpectedVersion($var)
    {
        GPBUtil::checkUint64($var);
        $this->expected_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string idempotency_key = 5;</code>
     * @return string
     */
    public function getIdempotencyKey()
    {
        return $this->idempotency_key;
    }

    /**
     * Generated from protobuf field <code>string idempotency_key = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setIdempotencyKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->idempotency_key = $var;

        return $this;
    }

}

