<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

namespace SpecDb\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * /v1/protobuf/search_full_specs/{query}
 *
 * Generated from protobuf message <code>specdb.query.SearchResultFullList</code>
 */
class SearchResultFullList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .specdb.query.SearchResultFull search_result_full = 1;</code>
     */
    private $search_result_full;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\SpecDb\Query\SearchResultFull>|\Google\Protobuf\Internal\RepeatedField $search_result_full
     * }
     */
    public function __construct($data = NULL) {
        \SpecDb\Metadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .specdb.query.SearchResultFull search_result_full = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSearchResultFull()
    {
        return $this->search_result_full;
    }

    /**
     * Generated from protobuf field <code>repeated .specdb.query.SearchResultFull search_result_full = 1;</code>
     * @param array<\SpecDb\Query\SearchResultFull>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSearchResultFull($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \SpecDb\Query\SearchResultFull::class);
        $this->search_result_full = $arr;

        return $this;
    }

}

