<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search.proto

namespace SpecDb\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>specs.SearchResult</code>
 */
class SearchResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>.specs.SpecType spec_type = 2;</code>
     */
    protected $spec_type = 0;
    /**
     * Generated from protobuf field <code>optional string human_name = 3;</code>
     */
    protected $human_name = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type int $spec_type
     *     @type string $human_name
     * }
     */
    public function __construct($data = NULL) {
        \SpecDb\Metadata\Search::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.specs.SpecType spec_type = 2;</code>
     * @return int
     */
    public function getSpecType()
    {
        return $this->spec_type;
    }

    /**
     * Generated from protobuf field <code>.specs.SpecType spec_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSpecType($var)
    {
        GPBUtil::checkEnum($var, \SpecDb\Query\SpecType::class);
        $this->spec_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string human_name = 3;</code>
     * @return string
     */
    public function getHumanName()
    {
        return isset($this->human_name) ? $this->human_name : '';
    }

    public function hasHumanName()
    {
        return isset($this->human_name);
    }

    public function clearHumanName()
    {
        unset($this->human_name);
    }

    /**
     * Generated from protobuf field <code>optional string human_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setHumanName($var)
    {
        GPBUtil::checkString($var, True);
        $this->human_name = $var;

        return $this;
    }

}

