<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

namespace SpecDb\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>specdb.query.SearchResultFull</code>
 */
class SearchResultFull extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>optional string human_name = 2;</code>
     */
    protected $human_name = null;
    protected $full_specs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $human_name
     *     @type \SpecDb\Query\GraphicsCard $graphics_card
     *     @type \SpecDb\Query\Cpu $cpu
     *     @type \SpecDb\Query\Apu $apu
     *     @type \SpecDb\Query\CpuArchitecture $cpu_architecture
     *     @type \SpecDb\Query\ApuArchitecture $apu_architecture
     *     @type \SpecDb\Query\GraphicsArchitecture $graphics_architecture
     *     @type \SpecDb\Query\GenericContainer $generic_container
     *     @type bool $hidden
     * }
     */
    public function __construct($data = NULL) {
        \SpecDb\Metadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string human_name = 2;</code>
     * @return string
     */
    public function getHumanName()
    {
        return isset($this->human_name) ? $this->human_name : '';
    }

    public function hasHumanName()
    {
        return isset($this->human_name);
    }

    public function clearHumanName()
    {
        unset($this->human_name);
    }

    /**
     * Generated from protobuf field <code>optional string human_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setHumanName($var)
    {
        GPBUtil::checkString($var, True);
        $this->human_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.specdb.query.GraphicsCard graphics_card = 3;</code>
     * @return \SpecDb\Query\GraphicsCard|null
     */
    public function getGraphicsCard()
    {
        return $this->readOneof(3);
    }

    public function hasGraphicsCard()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.specdb.query.GraphicsCard graphics_card = 3;</code>
     * @param \SpecDb\Query\GraphicsCard $var
     * @return $this
     */
    public function setGraphicsCard($var)
    {
        GPBUtil::checkMessage($var, \SpecDb\Query\GraphicsCard::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.specdb.query.Cpu cpu = 4;</code>
     * @return \SpecDb\Query\Cpu|null
     */
    public function getCpu()
    {
        return $this->readOneof(4);
    }

    public function hasCpu()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.specdb.query.Cpu cpu = 4;</code>
     * @param \SpecDb\Query\Cpu $var
     * @return $this
     */
    public function setCpu($var)
    {
        GPBUtil::checkMessage($var, \SpecDb\Query\Cpu::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.specdb.query.Apu apu = 5;</code>
     * @return \SpecDb\Query\Apu|null
     */
    public function getApu()
    {
        return $this->readOneof(5);
    }

    public function hasApu()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.specdb.query.Apu apu = 5;</code>
     * @param \SpecDb\Query\Apu $var
     * @return $this
     */
    public function setApu($var)
    {
        GPBUtil::checkMessage($var, \SpecDb\Query\Apu::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.specdb.query.CpuArchitecture cpu_architecture = 6;</code>
     * @return \SpecDb\Query\CpuArchitecture|null
     */
    public function getCpuArchitecture()
    {
        return $this->readOneof(6);
    }

    public function hasCpuArchitecture()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.specdb.query.CpuArchitecture cpu_architecture = 6;</code>
     * @param \SpecDb\Query\CpuArchitecture $var
     * @return $this
     */
    public function setCpuArchitecture($var)
    {
        GPBUtil::checkMessage($var, \SpecDb\Query\CpuArchitecture::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.specdb.query.ApuArchitecture apu_architecture = 7;</code>
     * @return \SpecDb\Query\ApuArchitecture|null
     */
    public function getApuArchitecture()
    {
        return $this->readOneof(7);
    }

    public function hasApuArchitecture()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>.specdb.query.ApuArchitecture apu_architecture = 7;</code>
     * @param \SpecDb\Query\ApuArchitecture $var
     * @return $this
     */
    public function setApuArchitecture($var)
    {
        GPBUtil::checkMessage($var, \SpecDb\Query\ApuArchitecture::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.specdb.query.GraphicsArchitecture graphics_architecture = 8;</code>
     * @return \SpecDb\Query\GraphicsArchitecture|null
     */
    public function getGraphicsArchitecture()
    {
        return $this->readOneof(8);
    }

    public function hasGraphicsArchitecture()
    {
        return $this->hasOneof(8);
    }

    /**
     * Generated from protobuf field <code>.specdb.query.GraphicsArchitecture graphics_architecture = 8;</code>
     * @param \SpecDb\Query\GraphicsArchitecture $var
     * @return $this
     */
    public function setGraphicsArchitecture($var)
    {
        GPBUtil::checkMessage($var, \SpecDb\Query\GraphicsArchitecture::class);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.specdb.query.GenericContainer generic_container = 9;</code>
     * @return \SpecDb\Query\GenericContainer|null
     */
    public function getGenericContainer()
    {
        return $this->readOneof(9);
    }

    public function hasGenericContainer()
    {
        return $this->hasOneof(9);
    }

    /**
     * Generated from protobuf field <code>.specdb.query.GenericContainer generic_container = 9;</code>
     * @param \SpecDb\Query\GenericContainer $var
     * @return $this
     */
    public function setGenericContainer($var)
    {
        GPBUtil::checkMessage($var, \SpecDb\Query\GenericContainer::class);
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool hidden = 10;</code>
     * @return bool
     */
    public function getHidden()
    {
        return $this->readOneof(10);
    }

    public function hasHidden()
    {
        return $this->hasOneof(10);
    }

    /**
     * Generated from protobuf field <code>bool hidden = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setHidden($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getFullSpecs()
    {
        return $this->whichOneof("full_specs");
    }

}

