<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

namespace SpecDb\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>specdb.query.SectionExtras</code>
 */
class SectionExtras extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, .specdb.query.Extra> extras = 1;</code>
     */
    private $extras;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $extras
     * }
     */
    public function __construct($data = NULL) {
        \SpecDb\Metadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, .specdb.query.Extra> extras = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getExtras()
    {
        return $this->extras;
    }

    /**
     * Generated from protobuf field <code>map<string, .specdb.query.Extra> extras = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setExtras($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \SpecDb\Query\Extra::class);
        $this->extras = $arr;

        return $this;
    }

}

