<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

namespace SpecDb\Query;

use UnexpectedValueException;

/**
 * Protobuf type <code>specdb.query.SpecType</code>
 */
class SpecType
{
    /**
     * Generated from protobuf enum <code>SPEC_TYPE_CPU = 0;</code>
     */
    const SPEC_TYPE_CPU = 0;
    /**
     * Generated from protobuf enum <code>SPEC_TYPE_APU = 1;</code>
     */
    const SPEC_TYPE_APU = 1;
    /**
     * Generated from protobuf enum <code>SPEC_TYPE_GRAPHICS_CARD = 2;</code>
     */
    const SPEC_TYPE_GRAPHICS_CARD = 2;
    /**
     * Generated from protobuf enum <code>SPEC_TYPE_CPU_ARCHITECTURE = 3;</code>
     */
    const SPEC_TYPE_CPU_ARCHITECTURE = 3;
    /**
     * Generated from protobuf enum <code>SPEC_TYPE_APU_ARCHITECTURE = 4;</code>
     */
    const SPEC_TYPE_APU_ARCHITECTURE = 4;
    /**
     * Generated from protobuf enum <code>SPEC_TYPE_GRAPHICS_ARCHITECTURE = 5;</code>
     */
    const SPEC_TYPE_GRAPHICS_ARCHITECTURE = 5;
    /**
     * Generated from protobuf enum <code>SPEC_TYPE_GENERIC_CONTAINER = 6;</code>
     */
    const SPEC_TYPE_GENERIC_CONTAINER = 6;
    /**
     * Generated from protobuf enum <code>SPEC_TYPE_HIDDEN = 7;</code>
     */
    const SPEC_TYPE_HIDDEN = 7;

    private static $valueToName = [
        self::SPEC_TYPE_CPU => 'SPEC_TYPE_CPU',
        self::SPEC_TYPE_APU => 'SPEC_TYPE_APU',
        self::SPEC_TYPE_GRAPHICS_CARD => 'SPEC_TYPE_GRAPHICS_CARD',
        self::SPEC_TYPE_CPU_ARCHITECTURE => 'SPEC_TYPE_CPU_ARCHITECTURE',
        self::SPEC_TYPE_APU_ARCHITECTURE => 'SPEC_TYPE_APU_ARCHITECTURE',
        self::SPEC_TYPE_GRAPHICS_ARCHITECTURE => 'SPEC_TYPE_GRAPHICS_ARCHITECTURE',
        self::SPEC_TYPE_GENERIC_CONTAINER => 'SPEC_TYPE_GENERIC_CONTAINER',
        self::SPEC_TYPE_HIDDEN => 'SPEC_TYPE_HIDDEN',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

