syntax = "proto3";

package specdb.cpu;

option php_namespace = "SpecDb\\Query";
option php_metadata_namespace = "SpecDb\\Metadata";

// CPU message
message Cpu {
    uint32 core_count = 1;
    uint32 thread_count = 2;
    string base_frequency = 3;
    string tdp = 4;

    // CPU Specific
    optional string boost_frequency = 5;
    optional string xfr_frequency = 6;
    optional string socket = 7;
    optional string stepping = 8;
    optional string l1_cache_data = 9;
    optional string l1_cache_instruction = 10;
    optional string l2_cache_total = 11;
    optional string l3_cache_total = 12;
    optional string memory_type = 13;

    optional uint32 pcie_5_0_lanes = 14;
    optional uint32 pcie_4_0_lanes = 15;
    optional uint32 pcie_3_0_lanes = 16;
    optional uint32 pcie_2_0_lanes = 17;
    optional uint32 pcie_1_0_lanes = 18;

    optional string avx_sse_mmx = 19;
    optional bool fma4 = 20;
    optional bool fma3 = 21;
    optional string bmi = 22;
    optional bool aes = 23;
    optional bool sha = 24;
    repeated string other_extensions = 25;
    optional bool unlocked = 26;
    optional bool xfr_support = 27;

    optional string max_memory_channels = 28;
    optional string max_memory_frequency = 29;
    repeated string compatable_chipsets = 30;

    // Hybrid architecture details
    optional string performance_core_base_frequency = 31;
    optional string efficient_core_base_frequency = 32;
    optional string performance_core_boost_frequency = 33;
    optional string efficient_core_boost_frequency = 34;
    optional uint32 performance_core_count = 35;
    optional uint32 efficient_core_count = 36;
    optional uint32 performance_thread_count = 37;
    optional uint32 efficient_thread_count = 38;
    optional bool ctdp_support = 39;
    optional string efficient_core_architecture = 40;

    // Shared
    optional string manufacturer = 41;
    repeated string market = 42;
    optional string architecture = 43;
    optional string lithography = 44;
    optional string release_date = 45;
}
